lib/index.js, test/system.test.js
Example for an error that will printed in the case of no permissions:
```
Permission denied connecting to docker daemon. Please make sure user has the required permissions. Error string:  Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.22/images/get?names=hello-world%3Alatest: dial unix /var/run/docker.sock: connect: permission denied
```
Previously it would print:
```
Docker image was not found: ubuntu:18.04
```
=> fix: better error when no permissions talking to docker

lib/index.js, package.json, test/system.test.js
before that fix, we would get a `TypeError` trying to access fields of `undefined`
=> fix: show better message when no Linux packages are detected

lib/analyzer/index.ts
In case we fail to analyse the image, we want to have a proper error msg to the user.
For example, on `busybox` - there is no proper PM, but the binaries of `rpm` + `dpkg` do exist, so we try to run `rpm` and get an usage error
https://snyksec.atlassian.net/secure/RapidBoard.jspa?rapidView=56&modal=detail&selectedIssue=SC-6675
=> feat: improve error msg on failure to analyze the image

lib/analyzer/os-release-detector.ts
Fix bug - for oracle:6 images like `oraclelinux:6`, the `OS.name` is 'ol ' and not 'ol'
=> fix: parsing oracle linux name

lib/index.ts
A little difficult to explain the precise reason for this change, but
currently the Snyk CLI has hacks in place to work around the different
format being returned for the binary results. The CLI shouldn't need
this level of knowledge / handling about the type of results.
=> fix: correctly return binaries analysis

lib/instruction-parser.ts, test/lib/instruction-parser.test.ts
=> fix: parse pkgs with hyphen in the name

lib/analyzer/binaries-analyzer.ts, lib/analyzer/binary-version-extractors/node.ts, lib/analyzer/binary-version-extractors/openjdk-jre.ts, lib/analyzer/index.ts, test/lib/analyzer/binaries-analyzer.test.ts
Adds package names for `openjdk-jre` according to package manager `APK`, `APT`, `RPM`.
Refactors logic by insertion of `installedByPackageManager` function into each binary `extractor` as it needs to be unique per binary.
snyk docker test any node image.
=> feat: check openjdk installed by pkg manager

lib/index.ts, package-lock.json, package.json, test/fixtures/dockerfiles/library/node/Dockerfile, test/system/system.test.ts
There is a mistake in the way we're building the tree in the `docker-plugin`:
While getting a list of deps from the analyzer, we're trying to build the tree of those deps (we're doing this part only in the `cli` and not in `docker-deps` - and that's the reason for the difference). On of the things that we missed, is a proper handling of *Providers*.  Providers are like categories of pkgs (in `deb`), for example: `c-compiler`.
In our case, we had a problem with the path `libtool -> gcc -> gcc-4.9 -> libgcc-4.9-dev -> libquadmath0`, cause we didn't see `libquadmath0` at the final deps list.
Let's look on the first dep - `libtool`:
```{
"Name": "libtool",
"Version": "2.4.2-1.11",
"Provides": [],
"Deps": {
"gcc": true,
"c-compiler": true,
"cpp": true,
"libc6-dev": true,
"libc-dev": true, …
```
=> fix: proper handling of providers

lib/analyzer/apk-analyzer.ts, lib/analyzer/apt-analyzer.ts, lib/analyzer/binary-version-extractors/node.ts, lib/analyzer/binary-version-extractors/openjdk-jre.ts, lib/analyzer/image-inspector.ts, lib/analyzer/os-release-detector.ts, lib/analyzer/rpm-analyzer.ts, lib/docker.ts, lib/index.ts, lib/sub-process.ts, test/lib/analyzer/apk-analyzer.test.ts, test/lib/analyzer/apt-analyzer.test.ts, test/lib/analyzer/binaries-analyzer.test.ts, test/lib/analyzer/image-inspector.test.ts, test/lib/analyzer/index.test.ts, test/lib/analyzer/os-release-detector.test.ts, test/lib/analyzer/rpm-analyzer.test.ts, test/lib/docker.test.ts, test/system/system.test.ts
Process may emit both stdout and stderr.
We currently only propagate one (giving precedence to stdout), potentially causing loss of data, e.g.:
```
Leons-MBP:snyk-docker-plugin leongold$ docker inspect foo:123
[] <--- stdout
Error: No such object: foo:123 <--- stderr
```
Refactor the project to return both in a single object, i.e {stdout, stderr}
=> fix: subprocess: include both stdout and stderr

lib/analyzer/apk-analyzer.ts, lib/analyzer/apt-analyzer.ts, lib/analyzer/binaries-analyzer.ts, lib/analyzer/binary-version-extractors/node.ts, lib/analyzer/binary-version-extractors/openjdk-jre.ts, lib/analyzer/image-inspector.ts, lib/analyzer/index.ts, lib/analyzer/os-release-detector.ts, lib/analyzer/rpm-analyzer.ts, lib/docker.ts, lib/index.ts, test/lib/docker.test.ts, test/system/system.test.ts
Added support for global docker options:
host (docker server: hostname:port)
tlsverify (verify tls: true/false)
tlskey (path to tls key)
tlscert (path to tls cert)
tlscacert (path to tls ca cert)
(snyk --docker --tlsverify=true --host=localhost:1234...)
entrypoint options are now being propagated all the way
through the docker module.
A couple of additional changes that had to take place:
1) We used to assume that if there's an inspection error,
it is due to missing images. This is no longer the case, and
this commit adds stderr output to the error messages.
2) the inspection module was using subprocess directly,
and it now uses the docker module wrapper in order to
also make use of the propagated options.
docker.ts
run docker's subprocess with some options …
=> feat: support global docker options

lib/docker-file.ts, lib/index.ts, test/lib/docker-file.test.ts
In order to support SCM Docker integration, this PR changes the way the Dockerfile is being parsed and analyzed, the `analyseDockerfile` function currently receives the path of the Dockerfile as an argument, but since in SCM integration the file system isn't available to `snyk-docker-plugin`, we must provide the actual contents of the Dockerfile instead of the path.
=> feat: alter analyse dockerfile by content to support SCM

lib/analyzer/binary-version-extractors/openjdk-jre.ts, test/lib/analyzer/binaries-analyzer.test.ts
Current JRE parsing logic is too restrictive:
1) Expects RE version to appear strictly in the 2nd line --
I'm now looking for "Runtime Environment" to determine the line.
This is merely a better heuristic, but it does fix adoptOpenJDK
detection.
2) Expects the output to be exactly 3 lines long.
I don't see the necessity.
=> fix: improve java binary analysis

lib/analyzer/binaries-analyzer.ts, lib/docker.ts, lib/index.ts
I've noticed (unfortunately post merge) that some of my changes
weren't included in the original PR (#61). I've included them now (and added
some stylistic changes)
Primarily what was missing in the original PR was options propagation to getRuntime
and to binaries extractor's extract method.
PR is verified via:
Leons-MBP:snyk leongold$ node dist/cli test --tlscacert=/Users/leongold/ca.pem --docker alpine
Testing alpine...
Docker error: could not read CA certificate "/Users/leongold/ca.pem": open /Users/leongold/ca.pem: no such file or directory
Leons-MBP:snyk leongold$
Leons-MBP:snyk leongold$ mv /Users/leongold/.docker/machine/machines/default/ca.pem ~/ca.pem
Leons-MBP:snyk leongold$ node dist/cli test --tlscacert=/Users/leongold/ca.pem --docker alpine
Testing alpine...
Organisation: …
=> fix: fix several docker option bugs

lib/analyzer/binary-version-extractors/openjdk-jre.ts
For backward compatibility java -version outputs to stderr, causing
open to return empty strings as we expected output in stdout.
Include both stdout and stderr when parsing java -version.
Reference:
https://stackoverflow.com/questions/17968856/redirect-to-stdout-in-bash
=> fix: return "java -version"'s both stdout and stderr

lib/index.ts, test/system/system.test.ts
While doing `snyk monitor --docker ubuntu@sha256:945039273a7b927869a07b375dc3148de16865de44dec8398672977e050a072e`
Actual result : image name is `ubuntu@sha256` and image tag is the sha256 itself
Expected result : image name is `ubuntu` and image tag is empty
=> feat: handle sha256 in image tag

lib/index.ts, lib/response-builder.ts, test/fixtures/analysis-results/deps.json, test/fixtures/analysis-results/dockerfile.json, test/fixtures/responses/all-deps.json, test/lib/response-builder.test.ts
We already have `exclude-base-image-vulns` option on the CLI side. It is causing us some issues because the processing is done post-fix and some metadata gets out of sync. This causes bugs related to: status code, summary fields, especially with combination with `json` option. Additionally, we want to move docker-specific logic into docker plugin, out of the general
Move application of `exclude-base-image-vulns` option from CLI to docker plugin to resolve bugs and improve code.
Start reviewing commit by commit - they should tell a story 😄.
Using `snyk test --docker image --file Dockerfile --exclude-base-image-vulns --json` with locally linked docker plugin version.
Dockerfile shouldn't introduce any new vulns, but base image should have some deps with vulns ([example …
=> Support for exclude-base-image-vulns plugin option

lib/analyzer/index.ts, lib/analyzer/os-release-detector.ts, lib/docker.ts, lib/index.ts, test/lib/analyzer/os-release-detector.test.ts
I did not find a way to detect scratch images without the help of Dockerfiles. Here are my proposed changes to support scratch images with the help of a Dcokerfile. Once we see "FROM scratch" in the dockerfile we basically skip past some tests and only perform the key-binary tests if we don't find a package manager.
=> fix: Support for scratch images

lib/index.ts
Scratch images will now have a "linux" package manager. This should just work with the current registry code.
=> fix: Scratch images have now a "linux" package manager

lib/analyzer/os-release-detector.ts, test/lib/analyzer/os-release-detector.test.ts
The Snyk DB stores Oracle vulns with single digit versions, but detection by the plugin was picking up a 2 digit version i.e. "7" instead of "7.6".
This patch adds some simple handle to ensure the oracle version is always single-digit
=> fix: Correctly detect oracle linux version

lib/docker-file.ts, lib/index.ts, lib/instruction-parser.ts, lib/response-builder.ts, package-lock.json, test/fixtures/dockerfiles/with-installation-instruction/Dockerfile, test/fixtures/responses/all-deps.json, test/lib/docker-file.test.ts, test/lib/response-builder.test.ts, test/system/system.test.ts
Introducing a structure (`dockerfileLayers`) that maps dockerfile layer digests to dockerfile install instructions. Additionally, the dependency tree is now annotated with dockerfile layer digests (using the new "labels" container (https://github.com/snyk/dep-graph/pull/19)
These two changes/additions will be directly used in displaying layer information for vulnerabilities in snapshots, as well as allowing us to filter base image vulnerabilities in the UI.
=> feat: introducing dockerfileLayers & annotating dep trees with layer ids

lib/instruction-parser.ts, test/lib/instruction-parser.test.ts
The instruction parser for Dockerfiles was failing in a couple of edge cases; this patch TDDs a solution for these missing cases.
=> fix: Remove flags from instruction parser

lib/index.ts, lib/response-builder.ts, test/fixtures/responses/all-deps.json, test/lib/response-builder.test.ts, test/system/system.test.ts
This plugin is now able to read multiple manifest files. Only the manifest files which could be found are included in the response.
=> feat: Reading of manifest files

lib/docker.ts, test/lib/docker.test.ts
In app scanning we had an onerous issue where we would sometimes return empty results for manifest files, even though files were present on image. This was tracked down to be an issue of error handling inside `runSafe()`.
Therefore, update `runSafe()` not to nullify stdout/stderr result, even if some command resulted in error code. This shouldn't change existing clients' behaviour, except for the case of listing multiple files (`ls -R /`). In that case some files might become inaccessible during long operation and make the command return error code (alongside valid stdout results). In this we return stdout/stderr to the caller, so the result can be used.
=> Fix app scan bug with undeterministical manifest files results

lib/extractor/layer.ts
The expectation until now was that files are extracted as "some/path/to/file.xyz".
Notice it didn't start with "/" so we prepended that to the filename.
However, using a RHEL image, files are named "./some/path/to/file.xyz", and if we just prepend "/" the path becomes "/./some/..." which will never match.
This fix now properly resolves paths by using path.resolve("/", `<the path>`) so that we get consistent paths regardless of relative paths.
=> fix: resolve paths in extracted files in docker-archive

lib/instruction-parser.ts, test/lib/docker-file.test.ts, test/lib/response-builder.test.ts
- use the package name w/o version as the dockerfile instruction key
- support apt-get -y options after the command position
- update tests to verify the label hook content
Dockerfile instruction parser
test and monitor an image with a dockerfile that includes a `RUN` line similar to:
`RUN apk add --no-cache --update git=2.18.1-r0`
=> fix: layers annotation when a package version is specified in instruction

lib/analyzer/static-analyzer.ts, lib/index.ts, lib/inputs/rpm/static.ts, lib/types.ts, test/lib/analyzer/rpm-input.test.ts
Do not infer a path where temporary files can be stored: this is problematic for the `kubernetes-monitor` because when the Kubernetes option readOnlyRootFilesystem is set, directories like /tmp become unusable.
Instead, the plugin now receives a path to a directory where it is safe to create temporary files.
=> feat: pass tmpdir path for static analysis

lib/analyzer/static-analyzer.ts, lib/index.ts, lib/types.ts, test/system/static.test.ts
To better capture the intention that some options in static analysis are required, change the types of the relevant fields.
=> fix: ensure some static analysis options are required

lib/analyzer/binary-version-extractors/node.ts, lib/analyzer/os-release/docker.ts, lib/docker.ts, lib/index.ts, lib/instruction-parser.ts, lib/ls-utils.ts, lib/response-builder.ts, package.json, test/lib/ls-utils.test.ts, test/system/system.test.ts
Follows: #123.
Change out `.forEach` for `for..of` where possible.
> `.forEach()` makes the stack-traces ugly, and messes with the ability to use `async`/`await`, which we're going to need in here soon.
at Object.keys.forEach (/srv/app/node_modules/snyk-docker-plugin/dist/index.js:359:9)
at countDepsRecursive (/srv/app/node_modules/snyk-docker-plugin/dist/index.js:358:23)
at Object.keys.forEach (/srv/app/node_modules/snyk-docker-plugin/dist/index.js:359:9)
at countDepsRecursive (/srv/app/node_modules/snyk-docker-plugin/dist/index.js:358:23)
=> feat: use for..of

lib/analyzer/binary-version-extractors/node.ts, lib/analyzer/os-release/docker.ts, package.json
https://github.com/rcjsuen/dockerfile-ast/pull/60
For now, pin us at typescript 3.6.
=> chore: typescript 3.7 breaks dockerfile-ast

lib/docker.ts, test/lib/docker.test.ts
Recursive listing of files (safeLs) is used for finding manifest files. Make this process more robust by handling expected errors/warning, such as permission denied. This allows for scanning to continue even if some (system) folders are inaccessible.
There's more we could do here for better error handling, but stopping sooner because upcoming switch to static scanning.
=> fix: Make safeLs more tolerant for expected errors

.circleci/config.yml
We have noticed that since `1.37.0` (when migrating to CircleCI) our published versions no longer include compiled js, but only typescript sources and these versions cannot be used in other projects.
This should fix it.
=> fix: Build process to include compiled js

lib/instruction-parser.ts, test/fixtures/dockerfiles/multi-stage-lowercase/Dockerfile, test/lib/docker-file.test.ts
Fixing an edge case where some/all instructions in the dockerfile are written in lowercase.
=> fix: correctly parse dockerfile written in lowercase

lib/docker.ts, lib/ls-utils.ts, package.json, test/lib/ls-utils.test.ts
Explicitly spin the event loop while looping over the found files, and just before parsing. This should improve responsiveness.
=> feat: spin the event loop during legacy scanning

lib/analyzer/image-inspector.ts, lib/docker.ts
BREAKING CHANGE:
Renamed .inspect() to inspectImage() in Docker class due to -
[DEP0079] DeprecationWarning: Custom inspection function on
Objects via .inspect() is deprecated
.inspect() is currently EOL
=> fix: rename .inspect() in Docker class due to deprecation

test/system/system.test.ts
currently the docker-plugin throws errors when scanning scratch images without Dockerfiles provided.
this test asserts the existing behaviour.
`snyk test --docker busybox`
https://www.notion.so/snyk/Improve-how-we-handle-scratch-images-6fe2d0dbb1584c69b2d185a0cee9e976
https://snyksec.atlassian.net/browse/RUN-709
=> test: proof that we do not support scratch image without docker file

lib/docker.ts, lib/ls-utils.ts, test/lib/docker.test.ts, test/lib/ls-utils.test.ts
- [x ] Ready for review
- [ x] Follows CONTRIBUTING rules
- [x ] Reviewed by Snyk internal team
This PR adds a special case to findGlobs to make it more efficient. The function now excludes system directories when it is called on the root directory.
https://snyksec.atlassian.net/browse/DC-382
=> fix: Exlcude system directories when calling findGlobs on the root path

.github/workflows/release-notes.yaml
will post an estimation of the release notes to each PR opened against the master branch, if a release should occur as a result of merging it.
https://github.com/snyk/release-notes-preview
=> chore: start using release-notes-preview to add visibility to release-notes

lib/experimental.ts, lib/index.ts, test/system/static.test.ts
In case we use the distroless flow in a static analysis contexts - don't use `docker save` to save the image and `docker pull` to pull it, just continue with the regular static analysis flow
=> fix: do not save distroless image in static scanning

lib/experimental.ts
Fixes the way we handle distroless scanning in static scanning flow
This was tested manually with a running kubernetes-monitor
=> fix: pass 'distroless' flag to static scanning

.circleci/config.yml
to match the minimal supported node version in Snyk cli
change test node version to 8, to match the minimal supported node version in Snyk cli
=> test: change test node version to 8

.circleci/config.yml
make semantic-release work with node 8
https://github.com/semantic-release/semantic-release/blob/master/docs/support/node-version.md#alternative-solutions
=> fix: make semantic-release work with node 8

.github/workflows/release-notes.yaml
bump release-notes-preview to 1.4.0 that is capable of discovering the ID of the tokened user instead of having to provide it.
=> chore: newer release-notes-preview that discovers userID alone

package.json, tsconfig.json
makes it easier to use the snyk-docker-plugin by exporting the types.
tested by installing this branch on the Kubernetes-Monitor and checking how it behaves in VSCode, as well as inspecting the index.d.ts file generated.
=> fix: export types for the plugin

lib/inputs/binaries/static/index.ts, lib/inputs/distroless/static.ts, test/lib/extractor/index.test.ts
minimatch is a heavy library that we don't need to call often. Instead we could use a simple string comparison to achieve the same thing in static scanning.
[Jira ticket RUN-861](https://snyksec.atlassian.net/browse/RUN-861)
=> fix: match file paths using string comparison instead of using minimatch

.github/workflows/release-notes.yaml, lib/experimental.ts
there's a race condition between deleting the image archive we save and scanning it because we do not ```await``` on the analysis before the ```finally``` clause is invoked.
adding an ```await``` in the proper place to fix it.
logging in the proper places
https://snyk.slack.com/archives/CDSMEJ29E/p1586348999177100?thread_ts=1586348254.175800&cid=CDSMEJ29E
🎫 🎟️
=> fix: race condition in the experimental scans for deleting the image

.github/workflows/release-notes.yaml
release-notes-preview should run on issue_comment edit, that's how it knows release notes were acknowledged
=> chore: release-notes-preview should run on issue_comment edit

lib/index.ts
add debug traces when dynamically scanning too many "app"-manifest files
https://github.com/snyk/snyk-docker-plugin/pull/181
https://snyk.slack.com/archives/CLB5WDQRF/p1586446845149000
=> fix: debug print when the limit on "app" manifest files is reached.

lib/dependency-tree/index.ts, lib/experimental.ts, lib/image-type.ts, lib/types.ts, test/lib/image-type.test.ts, test/system/experimental.test.ts, test/system/rpm.test.ts, test/system/static.test.ts
Allows to scan Docker archives as long as:
- the `experimental` flag is used
- the image is present on the filesystem
The image should be provided as `docker-archive:/path/to/archive.tar`.
[Jira ticket RUN-897](https://snyksec.atlassian.net/browse/RUN-897)
[Jira ticket RUN-877](https://snyksec.atlassian.net/browse/RUN-877)
=> feat/allow scanning existing Docker archives on the filesystem

lib/docker-file.ts
more precise typing for analyseDockerfile()
this function may only return a DockerFileAnalysis type, so there's no need for declaring it to be DockerFileAnalysis | undefined.
https://snyk.slack.com/archives/CGSNWAE76/p1588257666067100
=> fix: more precise typing for analyseDockerfile()

lib/analyzer/os-release/static.ts, lib/analyzer/static-analyzer.ts, lib/experimental.ts, lib/index.ts, lib/response-builder.ts, lib/static.ts, test/system/static.test.ts
Adds support for Dockerfile analysis when completing a static docker archive scan. This was a feature that was available previously when dynamically scanning the docker image.
The main advantage of this is that we can now retreive the base image used to build the container as long as the user provides us with the Dockerfile that was used to build it.
=> [RUN-660] feat: support dockerfile analysis during static scan

test/system/static.test.ts
introduction of the `docker` attribute to static scan results collided with type changes on `depTree` property of the scan results, causing this test to break.
https://github.com/snyk/snyk-docker-plugin/pull/198
https://github.com/snyk/snyk-docker-plugin/pull/195
https://snyk.slack.com/archives/CDSMEJ29E/p1588692621361000
`npm test`
=> chore: fix type safety in `static.test.ts`

.github/workflows/release-notes.yaml
update release-notes-preview with better GitHub token handling
no need to generate a token, this one uses the secret provided by GitHub Actions
=> chore: update release-notes-preview with better GitHub token handling

lib/extractor/layer.ts
today the static scan only scans files in the layers that are defined as "file", meaning we skip symbolic and hard links.
it's different from the dynamic scan that doesn't check for a file type.
moreover, it means we could miss some files in some circumstances.
this PR changes the static scan behaviour to also include links and symbolic links.
couldn't figure out why ```/etc/os-release``` isn't processed.
thanks to @shaimendel, discovered it's a symlink.
https://snyk.slack.com/archives/CDSMEJ29E/p1589115058473500
=> fix: scan symbolic and hard links in static image scans

lib/extractor/layer.ts
Reverts snyk/snyk-docker-plugin#202
the links found (at least the symbolic links) have no content generated from their stream, making this change useless/misleading.
=> Revert "fix: scan symbolic and hard links in static image scans"

lib/analyzer/static-analyzer.ts, lib/analyzer/types.ts, lib/inputs/file-pattern/static.ts, lib/static.ts, lib/types.ts, test/system/static.test.ts
first proposal for collecting arbitrary files (right now called manifestGlobs/manifestGlobsExclude) for the static scan.
https://snyksec.atlassian.net/browse/RUN-933
=> support retrieving arbitrary files for static scans

lib/inputs/rpm/docker.ts, test/lib/analyzer/rpm-analyzer.test.ts
allow one more type of rpm failures in dynamic scanning
=> fix: allow one more type of rpm failures in dynamic scanning

lib/index.ts, lib/inputs/file-pattern/static.ts, lib/types.ts, test/system/static.test.ts
Manifest files read from disk are kept in a Buffer instead of decoding them to a string.
This is to avoid encoding issues. See also: https://snyk.slack.com/archives/CBXS33GJY/p1589820258095800?thread_ts=1589385083.016900&cid=CBXS33GJY
=> fix: Manifest files are kept in a Buffer to avoid encoding issues

lib/analyzer/package-managers/apk.ts, test/fixtures/os/alpine_2_6_6/analyzer-expect.json, test/system/system.test.ts
we do it in order to better query vulns for alpine packages
we used to ignore package origins in apk, this fixes this
https://snyksec.atlassian.net/browse/RUN-987
=> [RUN-987] fix: add origin to apk packages

package.json
tsc-watch was missing as a devDependency so the debug script was not working.
Also replacing --debug-brk which was deprecated with --inspect-brk.
=> chore: update debug script in package.json to allow debugging

test/fixtures/dockerfiles/bug/Dockerfile, test/system/rpm.test.ts
Shows that there is a bug/limitation in the way we produce the dependencies for RPM projects.
Currently the dependencies are a flat list rather than a dependency tree or graph.
This means that transitive dependencies introduced by installing a package are not linked back to the Dockerfile instruction that introduced them.
[Jira ticket RUN-1009](https://snyksec.atlassian.net/browse/RUN-1009)
=> test: add tests to assert transitive deps are not found with RPM

README.md, lib/analyzer/image-inspector.ts, lib/analyzer/types.ts, lib/docker.ts, lib/experimental.ts, package.json, test/lib/analyzer/image-inspector.test.ts, test/system/static.test.ts
We want to remove the inherent reliance on the docker daemon when pulling container images from remote Docker v2 compliant repositories. This PR utilises the `snyk-docker-pull` lib to pull and save images to the local file system for scanning via the static scanning flow.
[RUN-994](https://snyksec.atlassian.net/browse/RUN-994)
=> [RUN-994] feat: pull images directly from docker registry API

lib/analyzer/static-analyzer.ts, lib/experimental.ts, lib/static.ts, lib/types.ts, test/system/application-scans.test.ts
Adding a flag to the docker plugin to activate parser based application scanning.
Add a flag next to the experimental flag to the CLI
See also this slack update: https://snyk.slack.com/archives/CLB5WDQRF/p1592497289002300
I open this at first as a draft PR since product needs to still decide about the actual name for the flag.
https://snyksec.atlassian.net/browse/DC-820
=> fix: Adding a flag to activate application scans

.circleci/config.yml
Change the node image for release step to 10. It will allow the semantic release works.
=> chore: fix the node image version for semantic release works

lib/analyzer/image-inspector.ts, lib/analyzer/types.ts, lib/docker.ts, lib/experimental.ts, package.json, test/lib/analyzer/image-inspector.test.ts, test/lib/experimental.test.ts, test/system/experimental.test.ts
Currently the plugin saves the downloaded image in a tmp folder. Now we allow the user to a custom location on disk with the best storage characteristics to download an image from a registry.
Includes the option `imageSavePath` that if is set indicate the path where the downloaded image should be save.
You should follow the flow when the flag `--experimental` is set.
You can create a manual test and pass in the options `imageSavePath` with where you'd like to save the image. Be aware that it's a temporary file and the image will be removed once it finishes.
It's good to notice when the image doesn't exist in local and there is no docker binary, it will pull the via `snyk-docker-pull`. It was changed to do the same.
- [RUN-582](https://snyksec.atlassian.net/browse/RUN-582)
- …
=> feat: allow to choose the image save path for downloaded image

.gitignore, package.json
`event-loop-spinner@2` brings better sharing, which should reduce overall blocking for everyone, especially across library. It requires node 8, and so should we.
=> feat: event-loop-spinner for fewer blocky blocks

lib/analyzer/docker-analyzer.ts
Fixing a bug, where `map` in called on an undefined object.
=> fix: Check normalized paths if undefined

package.json, test/fixtures/analysis-results/yarn.json
Updating nodejs-lockfile-parser to prevent including our lodash fork.
JIRA: HAMMER-99
=> fix: update nodejs-lockfile-parser to use upstream lodash

.circleci/config.yml, lib/analyzer/image-inspector.ts, test/lib/analyzer/image-inspector.test.ts, test/system/static.test.ts
Fixed getImageArchive() so the logic doesn't depend on the function throwing errors.
First commit refactors `getImageArchive()` so the logic doesn't depend on the function throwing errors, the code is hopefully more readable and it can be extended easier. 
`Update tests for ARM` commit: we're removing a test depending on an experimental docker feature and adding a test covering scanning an ARM based image.
And last commit we're adding the error handling for `docker --platform`. We're throwing only when we get a specific error from `docker pull`: `unknown operating system or architecture`, otherwise if `pull` or `save` fails for any other reason we want to fall back to pulling using our pull lib.
Commit by commit please!
https://snyksec.atlassian.net/browse/RUN-1162
=> Adding error handling for `docker --platform`

package.json
This snyk-nodejs-lockfile-parser upgrade uses the newer uuid library,
which we're already using. (uuid 8)
=> feat: upgrade node-lockfile-parser (uuid upgrade)

lib/analyzer/image-inspector.ts, lib/docker.ts, test/lib/docker.test.ts
We support the '--platform' flag only when Docker experimental features enabled, throwing a user friendly error otherwise.
https://snyksec.atlassian.net/browse/RUN-1197
=> feat: [RUN-1197] Fail if Docker not experimental

lib/display.ts, lib/types.ts, package.json, test/fixtures/display/deb-dep-graph.json, test/fixtures/display/output/a-few-issues.txt, test/fixtures/display/output/no-issues-with-file-options.txt, test/fixtures/display/output/no-issues.txt, test/fixtures/display/output/only-base-image-remediations.txt, test/fixtures/display/scan-results/rpm.json, test/fixtures/display/test-results/only-base-image-remediation.txt, test/fixtures/display/test-results/with-few-issues.txt, test/lib/display.test.ts
As part of the envelope project, now the plugin is responsible to format the scanned information to be displayed. It gives more flexibility for the plugins owners to format the information.
Create the first iteration for the `display()` function that formats the scanned results.
The `display()` function handles only the human readable output.
For the specific `display()` test, you can run `npx tap test/lib/display.test.ts -R=spec --timeout=300`
As part of the project envelope, the plugin got the responsibility to format the scanned results to be displayed. 
[RUN-1175](https://snyksec.atlassian.net/browse/RUN-1175)
=> feat: display the scan result formatted

lib/display.ts, test/fixtures/display/output/a-few-issues.txt, test/fixtures/display/output/no-issues-with-file-options.txt, test/fixtures/display/output/no-issues.txt, test/fixtures/display/output/only-base-image-remediations.txt, test/fixtures/display/scan-results/rpm.json
When 'snyk container test', we want to see platform information in the scan output. With the new flow, CLI will call `display()` in the plugin to get the output string.
https://snyksec.atlassian.net/browse/RUN-1148
=> feat: Add platform info to the CLI output

package.json
Include `chalk` dependency.
It was missing as a prod dependency and `tap` was brought it during the local and CI test. However it won't work when some application, like the CLI, tries to run it.
`rm -rf dist && rm -rf node_modules && npm install`
=> fix: the plugin was missing dependency

lib/experimental.ts, test/system/experimental.test.ts
Converts `boolean|string` parameter received from cli input to `boolean` at point where interface requires `boolean`
Examples:
```
snyk test --docker --experimental --app-vulns=false mladkau/snykin
```
1) from snyk/snyk-docker-plugin run `npm run build`
2) from snyk/snyk project run `npm link /path/to/snyk-docker-plugin`
3) from snyk/snyk project run `npm run build`
4) from snyk/snyk for os vuln test:
* `node dist/cli test --docker --experimental mladkau/snykin`
* `node dist/cli test --docker --experimental --app-vulns=false mladkau/snykin`
5) from snyk/snyk for app+os test:
* `node dist/cli test --docker --experimental --app-vulns mladkau/snykin`
* `node dist/cli test --docker --experimental --app-vulns=true mladkau/snykin`
* [DC-852](https://snyksec.atlassian.net/browse/DC-852)
`node …
=> fix: corrected app-vulns flag parsing

package.json
Pick up a minor release of `snyk-nodejs-lockfile-parser`, which we have pinned.
This version bump brings the removal of source-map-support, which is inappropriate behaviour for a library.
=> feat: upgrade node lockfile parser (dropping weird transitive)

lib/index.ts, test/lib/display.test.ts
Export `display()` to be used by the Snyk CLI for issues output.
This function up until now was only used internally but needs to be accessible by the CLI.
=> fix: export display() to be used by the Snyk CLI for issues output

jest.config.js, package.json
Attempt to fix a `ts-jest` (caused by `jest`) memory leak with a workaround.
[Slack thread](https://snyk.slack.com/archives/CLW30N31V/p1602232569018000?thread_ts=1602230753.017500&cid=CLW30N31V)
=> chore: fix CI/CD Jest memory leak with a workaround

lib/scan.ts, lib/types.ts, test/system/flags/image-name-and-tag.spec.ts
Override the "name" and "version" fields of the OS dependencies result when scanning image archives.
This is NOT used by the Snyk CLI!
It is used by K8s-Monitor and DRA to preserve the image identifier when scanning archives.
The archives do not contain any data about the image's name and tag (since they are only known by the container registry) and in some contexts we know this data and want to keep it.
[Jira ticket RUN-1220](https://snyksec.atlassian.net/browse/RUN-1220)
=> feat: add flag imageNameAndTag to preserve this data in archive scans

lib/analyzer/image-inspector.ts, test/lib/analyzer/image-inspector.test.ts
On some platforms like Windows we're getting race conditions when we synchrony remove folders. To avoid that we're removing it in async mode.
The problem seems to happen only in the CI when running tests for Windows platform [here](https://app.circleci.com/pipelines/github/snyk/snyk/2820/workflows/8dc49982-9d50-4c66-ab4a-245a94cd6783/jobs/15580).
[Slack thread](https://snyk.slack.com/archives/CDSMEJ29E/p1603218013373900)
=> fix: avoid race condition to remove pulled image and tmp folder

test/system/bugs/Dockerfile.injected, test/system/bugs/injected-dockerfile-base-image.spec.ts
If the base image name and tag are injected using ARG in the Dockerfile, the analysis will incorrectly mark the baseImage as null:null.
[ZenDesk ticket 7256](https://snyk.zendesk.com/agent/tickets/7256)
=> test: show a bug exists with injected base image in Dockerfiles

test/README.md
Also include instructions for tidying up leftover temp files
The old repo does not exist as a private repo; the new one does. That caused tests to fail.
This is required to run tests locally
RUN-1041
=> docs: correct env var values for tests

package.json
Updates to the new snyk-config version that should get shipped with the CLI first.
Requirement for snyk/snyk#1524
Follow up to the snyk/config#43 and https://github.com/snyk/nodejs-lockfile-parser/pull/89
=> fix: update nodejs-lockfile parser

test/system/app-os/__snapshots__/globs.spec.ts.snap, test/system/app-os/globs.spec.ts, test/system/static.test.ts
The image `debian:10` was modified on
the public repo, causing a test to fail.
Our test expectation has been updated to match
the new correct value, and pinned to a specific
hash.
Similarly, the image `opensuse-leap:15.1` was modified on
the public repo. This change affected the number
of dependencies, causing a test to fail.
So our test expectation has been updated to match
the new correct value.
=> refactor: Update test expectations

lib/scan.ts, test/lib/scan.spec.ts, test/system/registry-authentication/__snapshots__/username-password.spec.ts.snap, test/system/registry-authentication/username-password.spec.ts
[RUN-1041] Setting SNYK_REGISTRY_USERNAME and/or SNYK_REGISTRY_PASSWORD environment variables allows these credentials to be used to log in to remote registries. The existing --username and --password flags, if present, take precedence
Documentation updates will follow in a separate PR
[RUN-1041]: https://snyksec.atlassian.net/browse/RUN-1041
=> Use ENV for credentials for downloading images on CLI

lib/analyzer/static-analyzer.ts, lib/extractor/callbacks.ts, lib/extractor/layer.ts, lib/extractor/types.ts, lib/go-parser/index.ts, lib/inputs/file-pattern/static.ts, lib/stream-utils.ts, package.json, test/lib/stream-utils.test.ts
refactor: Extract only not empty layers
Before, applyCallbacks result was always defined, because we were matching on file path. For Go modules parsing, we also match on the filepath, but now the callback function does not necessarily return a result and we are filtering the undefined results out.
feat: Identify go binaries
We're identifying go binaries which are ELF executables, which are then returned as extractedLayers. No results from go modules are being processed into a scanResult yet.
Commit by commit, the first one is a refactor and the second one we're adding go binaries extraction.
https://snyksec.atlassian.net/browse/RUN-1271
=> [RUN-1271] Feat/identify go binaries

lib/analyzer/applications/types.ts, lib/analyzer/static-analyzer.ts, lib/extractor/index.ts, lib/extractor/types.ts, lib/go-parser/index.ts, lib/go-parser/parser.ts, lib/go-parser/str-tab-parser.ts, lib/go-parser/types.ts, lib/go-parser/version-parser.ts, lib/inputs/index.ts, package.json, test/system/application-scans/__snapshots__/gomodules.spec.ts.snap, test/system/application-scans/gomodules.spec.ts, test/system/application-scans/java.spec.ts, test/system/application-scans/node.spec.ts, test/system/bugs/rpm-transitive-dependencies.spec.ts, test/system/flags/image-name-and-tag.spec.ts, test/system/image-type/compressed-archive.spec.ts, test/system/image-type/docker-archive.spec.ts, test/system/image-type/oci-archive.spec.ts, test/system/key-binaries-hashes/hashes.spec.ts, test/util/index.ts, test/windows/application-scans.spec.ts, test/windows/plugin.spec.ts
Add support to scan `non-stripped` Go binaries
Algorythm: 
1. Find binaries in the image
2. Check if the binary is ELF executable.
3. Get relevant ELF sections and programs.
4. Parse them.
5. Build DepGraph
=> feat: parse go binary and get dependency graph for this binary

.gitignore, lib/scan.ts, test/lib/scan.spec.ts
Most of the docker commands implicitly add `latest` to images without tags. In case of `docker save`, the behavior is not the same and can result in performance issues as well as inconsistent results.
Using `scan` with/without latest tag, with multiple different images from the same repo, should result in the same `scanResults`
=> Append latest if an image without a tag was provided

lib/extractor/index.ts, lib/extractor/types.ts, test/system/dockerfile-analysis/__snapshots__/dockerfile.spec.ts.snap, test/system/image-type/__snapshots__/oci-archive.spec.ts.snap
This is a fixup after #319:
* Update oci-archive extractor not to return empty image labels, because we don't extract them yet.
* For docker-archive, extract labels and always return `imageLabels` fact.
This allows clients to differentiate between these situations:
* `imageLabels` fact is present, data isn't empty: image has labels
* `imageLabels` fact is present, data is empty: image has no labels
* `imageLabels` fact isn't present: we have no information on labels, didn't extract them
Once oci-archive label extraction is implemented, there will be only first two possible situations.
=> chore: Don't return empty labels for oci-archive images

lib/extractor/docker-archive/index.ts
For docker archives we extract auto detected user instructions from the image config. Some of the entries are missing "created_by" so we were throwing an error - this PR is fixing that.
=> fix: Added filtering history entries with no "created_by"

lib/dockerfile/index.ts, lib/dockerfile/instruction-updater.ts, lib/dockerfile/types.ts, test/lib/dockerfile/index.spec.ts
Introduces new api to update a dockerfile's base image with a user supplied image.
This implementation only supports updating FROM and ARG instructions that contains whole image names.
* DC-1135
=> feat: update dockerfile with new base image

lib/index.ts
It exports functions and types that are used in Docker Deps
Docker Deps is importing some function functions and types from the `dist` folder. Because these functions and types were not being properly exported in Snyk Docker Plugin. 
[CAP-219](https://snyksec.atlassian.net/browse/CAP-219)
=> fix: export functions and types

test/system/bugs/centos6.spec.ts
This bug happens because the image in question has 2 OS release files - lsb_release and centos_release.
Our detection logic runs the LSB parser first. Unfortunately, in this specific image lsb_release is malformed and does not contain enough information about the OS release. The real OS release data is in centos_release, but our parser throws an error before examining it.
[Jira ticket #9475](https://snyk.zendesk.com/agent/tickets/9475)
I'll create the follow up fix for this :)
=> test: show bug with being unable to scan CentOS 6 images

lib/analyzer/os-release/static.ts, test/system/operating-systems/__snapshots__/centos6.spec.ts.snap, test/system/operating-systems/centos6.spec.ts
This is instead of the current implementation of failing on the first OS release parser.
Some images may contain multiple OS release files. One of them would be malformed, whereas the other would contain the data for the OS release.
This change ensures all handlers get the chance to run and try and parse the OS release.
[Jira ticket #9475](https://snyk.zendesk.com/agent/tickets/9475)
[PR #330: test: show bug with being unable to scan CentOS 6 images](https://github.com/snyk/snyk-docker-plugin/pull/330)
=> fix: best-effort attempt to read OS release files

package.json
Updated snyk-docker-pull which has an updated version of docker-registry-v2-client that fixed an issue when getting multiarch manifest by its digest returning a manifest list, which resulted in a 'cannot read property of undefined' exception, when trying to access the manifest.config.digest object (as there is no config object in manifest list).
The latest fix in the v2-client lib makes sure the getManifest always returns a manifest.v2 object rather than a list (in case a list is returned by the API call the default linux/amd64 arch is chosen and returned by it).
An open ticket in snyk CLI: https://github.com/snyk/snyk/issues/1892
Internal Jira ticket: https://snyksec.atlassian.net/browse/DC-1219 
https://github.com/snyk/docker-registry-v2-client/pull/62 …
=> fix: Update snyk-docker-pull to fix exception [DC-1219]

package.json
This PR updates snyk-docker-pull which has an updated version of docker-registry-v2-client, as latest update in docker-registry-v2-client includes a performance improvement that reduces the amount of API calls in getManifest, in some scenarios.
More information about the improvement can be found in the docker-registry-v2-client PR: https://github.com/snyk/docker-registry-v2-client/pull/63
https://snyksec.atlassian.net/browse/DC-1219
=> fix: Update snyk-docker-pull to improve performance [DC-1219]

package.json
Update snyk-docker-pull to update docker-registry-v2-client to enable setting needle default timeout through environment variable.
https://github.com/snyk/docker-registry-v2-client/pull/64
https://snyksec.atlassian.net/browse/DC-1162
=> fix: Update snyk-docker-pull to v3.2.8

lib/analyzer/image-inspector.ts, test/lib/analyzer/image-inspector.spec.ts
This PR checks if the image argument passed by the user via the CLI is an existing image and throws an error if it could not be analysed.
From the cli:
$ node dist/cli container test /does-not-exist
$ node dist/cli container test does-not-exist
See [CAP-228 ](https://snyksec.atlassian.net/browse/CAP-228)
=> fix: Handle container test with invalid image [CAP-228]

lib/analyzer/types.ts, lib/extractor/docker-archive/index.ts, lib/extractor/types.ts, lib/facts.ts, lib/index.ts, lib/types.ts
Updates domain to reflect that AutoDetectedUserInstructions does not have a base image.
This is preparation for adding parsing errors to DockerFileAnalysis.
=> fix: split auto detected user instructions and dockerfile analysis type

package.json
Bumps pull library, which in turn has a bumped docker-v2 library upgrade, which contains these fixes:
snyk/docker-registry-v2-client#74
Some CRs return a redirect URI with just the path
(without the hostname), which breaks our redirect handling which is
expecting a full URL. This fix adds the hostname and protocol in case
they are missing
snyk/docker-registry-v2-client#75
When the content type is wrongly set to text instead of binary, response
body is returned as string instead of a buffer. This forces a buffer
response
=> fix: bump pull library with fixes

lib/dockerfile/instruction-parser.ts, lib/types.ts, test/lib/dockerfile/index.spec.ts
Allow base image to be partially missing
In some cases where the base image in the Dockerfile's FROM instruction contains arguments that are substituted at build-time, we would incorrectly detect the base image as /image:tag which is a bad user experience. We fix this by ensuring that we report the base image only if we can read every variable in the FROM instruction, while keeping the old handling for package instruction parsing.
Co-authored-by:@ahmed-agabani-snyk
=> feat: allow base image to be partially missing

package.json
Runs both `tap` and `jest` tests when running `npm run test`.
> npm run test
watch all the tests run 🤩
=> chore: run also jest upon npn run test

lib/analyzer/applications/java.ts, lib/analyzer/applications/types.ts, lib/analyzer/static-analyzer.ts, lib/buffer-utils.ts, lib/inputs/index.ts, lib/inputs/java/static.ts, lib/stream-utils.ts, test/lib/analyzer/java.spec.ts, test/lib/buffer-utils.spec.ts, test/lib/inputs/index.spec.ts
Return a Buffer rather than sha from the extract actions, and only convert to sha during later processing.
This is required before will are able to extend the later processing with unpacking the jar within the next task
can be reviewed commit-by-commit. main changes are in first commit, and later commits are more refactoring and tests.
run a scan on image with jars, note that output should be the same on master and on this branch.
Part of "UberJars" work to support nested jars.
CAP-409
=> refactor: jar extract action to return a Buffer

lib/analyzer/os-release/release-analyzer.ts, test/fixtures/os/redhat_6_5/fs/etc/redhat-release, test/fixtures/os/redhat_7/fs/etc/os-release, test/fixtures/os/redhat_7/fs/etc/redhat-release, test/lib/analyzer/os-release-detector.spec.ts
Fixes the detection of RedHat OS in RedHat 6 images.
Yes
https://snyk.zendesk.com/agent/tickets/14148
=> fix: Release analyzer should return the right code

package.json
This PR is bumping docker-pull version to @snyk/snyk-docker-pull@3.7.1, which removes the optimization that chooses when to accept manifest list content type and instead always accept it, to tackle snyk/snyk#2359 - needed for ECR.
See as well: https://github.com/snyk/docker-registry-v2-client/pull/84
=> fix: Bump docker-pull version to 3.7.1

package.json
This PR upgrades the version of snyk-nodejs-lockfile-parser from 1.36.0 to 1.37.2. 
This is done to support deeply out of sync lockfiles, added in v1.37.0.
https://snyk.slack.com/archives/C01EPSMGZML/p1639590254212300
=> fix: upgrade snyk-nodejs-lockfile-parser from 1.36.0 to 1.37.2

lib/analyzer/static-analyzer.ts, lib/scan.ts, lib/types.ts, test/system/application-scans/java.spec.ts
we realized that "shaded-jars" to speak about "nested jars" (jars inside jar)  is not the correct term.
We don't want to break backwards compatibility, so adding the alias. in the future we will only document
--nested-jars-depth, and will ask those who use --shaded to switch.
> **uber jar** is also known as **fat jar** i.e. **jar with dependencies.**There are three common methods for constructing an uber jar:
>
> **Unshaded:** Unpack all JAR files, then repack them into a single JAR. Works with Java's default class loader. Tools [maven-assembly-plugin](http://maven.apache.org/plugins/maven-assembly-plugin/)
>
> **Shaded:** Same as unshaded, but rename (i.e., "shade") all **packages** of all dependencies. Works with Java's default class loader. Avoids some (not all) dependency version …
=> feat: add alias nested-jars-depth in addition to shaded-jars-depth

lib/analyzer/applications/java.ts, lib/analyzer/applications/types.ts, lib/analyzer/types.ts, test/fixtures/pom-properties/incomplete.pom.properties, test/fixtures/pom-properties/invalid.pom.properties, test/fixtures/pom-properties/valid.pom.properties, test/lib/analyzer/java.spec.ts, test/system/application-scans/__snapshots__/java.spec.ts.snap, test/util/index.ts, test/windows/__snapshots__/application-scans.spec.ts.snap
Extract information from unpacked JAR pom files and pass the discovered dependencies to maven to be added to the depGraph. This information will be used to query the vulnDB to find possible vulns for the packages from jar pom files.
=> feat: Return jar dependecies from pom files

lib/analyzer/static-analyzer.ts, lib/scan.ts, lib/types.ts, test/system/application-scans/java.spec.ts
Step #1 for detecting log4j automatically for customers who scan images with shaded and nested jars.
The end goal is to have always at least 1 level scanned, 
see here https://www.notion.so/snyk/log4shell-shaded-Jar-detection-552bed54e8964a968867c601905f80a0#723610c656e7467684a6cbf62f84322d and here https://snyk.slack.com/archives/C01EPSKVC9L/p1639908202242500?thread_ts=1639765350.234600&cid=C01EPSKVC9L
The first step (in this PR) is making the default level of unpacking 1 (instead of 0, which it once was).
The second step would be to unpack 1 level _more_ than what the customer requested, so we can get the pom.properties (the shaded jars) for that level of nesting.
=> Default nested

lib/analyzer/static-analyzer.ts, lib/scan.ts, lib/types.ts, test/system/application-scans/java.spec.ts
Allowing the CLI users to opt-out and use `--nested-jars-depth=0` to not unpack any levels of JARs.
=> fix: bring back option for nested-jars-depth=0

lib/analyzer/applications/java.ts, test/lib/analyzer/java.spec.ts
This PR catches any errors coming from admzip and continues
with the next JAR. The JAR that causes unzip errors will still
be included in the fingerprints as expected.
=> fix: Catch errors with admzip

.circleci/config.yml
This PR upgrades the legacy CircleCI convenience image circleci/node
to the next-gen cimg/node image for the build pipeline. The image is
tagged at 14.18.
[https://circleci.com/docs/2.0/next-gen-migration-guide/](https://circleci.com/docs/2.0/next-gen-migration-guide/)
[https://circleci.com/developer/images/image/cimg/node](https://circleci.com/developer/images/image/cimg/node)
See [[CAP-432](https://snyksec.atlassian.net/browse/CAP-432)]
=> fix: Upgrading CircleCI build image

lib/extractor/docker-archive/index.ts, lib/extractor/docker-archive/layer.ts, lib/extractor/index.ts, lib/extractor/oci-archive/layer.ts, lib/extractor/types.ts, package.json, test/system/dockerfile-analysis/__snapshots__/dockerfile.spec.ts.snap, test/system/image-type/__snapshots__/oci-archive.spec.ts.snap
The OCI Archive scanning was not collecting the image config, so we were missing lots of good information from the image, such as root fs layers, auto-detected user instructions, platform, and image labels. The config is now properly detected and we can read this data.
=> feat: scan image config for oci archives to get rootFs, platform, etc.

lib/stream-utils.ts
Whenever we attempted to parse oci-archive files, we first loaded any file we encountered in memory fully before we JSON-parsed it.
Some files may be really large and may consume lots of memory.
Introduce a hard limit to read only up to 2 MiB of the file and to attempt to parse the result.
=> fix: ensure large objects are not loaded in memory when parsing them

lib/analyzer/image-inspector.ts, test/lib/analyzer/image-inspector.spec.ts
Removes the async keywork from the function extractImageDetails which doesn't use await inside it.
=> fix: remove unnecessary async keyword from extractImageDetails

lib/analyzer/applications/java.ts, lib/analyzer/applications/types.ts, test/system/application-scans/java.spec.ts
Refactored the recursion of unpacking nested JARs to avoid mutating objects
which was difficult to follow and caused incorrect dependency allocation
in the fingerprints facts which resulted in an invalid dep-graph.
=> fix: Fixed invalid jar fingerprints for maven projects

.circleci/config.yml
- removed the test-jest job from the test and release workflow, since
`test-jest` is already a part of the `test` script, and it's redundant
to run it twice.
- only run tests after lint and build are done to avoid running the
tests on a broken code
=> chore: align ci test flow

lib/analyzer/applications/index.ts, lib/analyzer/applications/php.ts, lib/analyzer/static-analyzer.ts, lib/inputs/php/static.ts, lib/scan.ts, package.json, test/system/application-scans/__snapshots__/php.spec.ts.snap, test/system/application-scans/php.spec.ts
Adds support for scanning `composer` (PHP) manifest files directly in the plugin.
Using the CLI / DRA, run a scan on an app+os image containing PHP manifest files. Both should result with the same vulns for both app and OS.
[MYC-82](https://snyksec.atlassian.net/browse/MYC-82)
=> php app vulns [MYC-82]

lib/go-parser/index.ts, package.json, tsconfig.json
Build started failing all of a sudden, probably because we have no
package-lock file in this project. To fix the tsc build problem, this
commit upgrades typescript, and replaces empty `resolve` statements to
`resolve(undefined)`, since otherwise it throws a type error.
=> fix: upgrade typescript dependency

lib/analyzer/applications/php.ts, test/system/application-scans/__snapshots__/php.spec.ts.snap
when scanning PHP (composer) manifest files, we need to set the target
file as the lock file rather than the json file, to be consistent with
other ways of creating PHP projects
How it should be:
How it is without this fix
=> fix: php target file

package.json, test/lib/analyzer/image-inspector.spec.ts
Since Snyk's CLI current minimum supported version is 12, the plugin
should also support that version. Then only piece of code that was using
a Node >= 14 code was the use of `rmSync` in one of the tests, and this
was adjusted here.
=> fix: downgrade minimum nodejs version to 12

lib/analyzer/package-managers/rpm.ts, lib/analyzer/static-analyzer.ts, lib/inputs/rpm/static.ts, package.json, test/system/package-managers/__snapshots__/rpm.spec.ts.snap, test/system/package-managers/rpm.spec.ts
As of rpm>=4.16 the installed packages are now stored in an SQLite DB instead of a Berkeley DB.
This adds support for these images to return the correct list of the image's dependencies.
=> feat: support for image with RPM>=4.16

lib/inputs/rpm/static.ts, package.json
`rpm-parser` now using `sql.js` instead of `sqlite` due to limitations in Snyk CLI. 
Mainly removals since it supports opening the DB from Buffer.
=> fix: bump rpm parser

package.json
Upgrade to the recent version of @snyk/dep-graph, which has dropped support for node 8, which we haven't cared about for a long time.
=> feat: new @snyk/dep-graph (no more node 8)

lib/go-parser/version-parser.ts, package.json, test/system/application-scans/__snapshots__/gomodules.spec.ts.snap, test/system/application-scans/gomodules.spec.ts, test/unit/go-version-parser.spec.ts, tslint.json
Fixes an issue where we don't detect go modules from go binaries built
with go version >= 1.18. Adapted the version parser to accommodate for
different structure.
The `if` statement from [here](https://github.com/golang/go/blob/master/src/debug/buildinfo/buildinfo.go#L174) was missing in our code, and therefore we were not parsing the binary file correctly.
There are also some minor refactors here to make the code more like the original Go code, and for readability.
See ticket for example image that has one binary detected and one that isn't
https://snyksec.atlassian.net/browse/MYC-131
=> Fix go modules detection [MYC-131]

lib/analyzer/image-inspector.ts, lib/docker.ts, test/lib/analyzer/image-inspector.spec.ts, test/lib/docker.test.ts
Mainly removes the check if Docker experimental is enabled if the user specifies a platform. It's not needed anymore as the `--platform` flag for `docker pull` has been graduated to stable. Also some clean-up around that feature.
https://snyksec.atlassian.net/browse/MYC-117
=> No experimental check for platform setting [MYC-117]

test/system/index.spec.ts, test/system/operating-systems/alpine3.7.spec.ts, test/system/operating-systems/centos7.spec.ts, test/system/operating-systems/sles15.spec.ts, test/system/operating-systems/ubi8.spec.ts, test/system/package-managers/apk.spec.ts, test/system/package-managers/deb.spec.ts, test/system/package-managers/rpm.spec.ts, test/system/plugin.test.ts, test/system/static.test.ts
This PR improves the unit- and integration-tests and makes them work
on non-AMD64 platforms as well (like Apple's M1). For most tests, it
simply specifies the target platform to always be AMD64. For some
unit-tests, it changes the image tags to instead use the digests of the
AMD64 images.
If you have an M1 or M2 laptop, run `npm run test` locally.
[MYC-116](https://snyksec.atlassian.net/browse/MYC-116)
=> test: fix tests on ARM (MYC-116)

lib/analyzer/package-managers/rpm.ts, package.json, test/lib/analyzer/package-managers/rpm.spec.ts, test/system/package-managers/__snapshots__/rpm.spec.ts.snap
When we change the structure of the packages for creating the dep graph, need to reformat the version to include the release and epoch parts as well. 
This fixes an issue with vuln matching.
Tests describing the change.
=> fix: final rpm version string should include epoch and release

.circleci/build-go-binary-latest.sh, test/fixtures/go-binaries/source/build.sh
`==` is a bashism, `=` is the shell equivalent. Interestingly, when run
on MacOS, `==` works as well, which is why local testing didn't bring up
this issue.
Further, `@*` concatenates the array of arguments into a single variable
seperated by the `IFS`, which is a space. So the end result should be
the same.
These changes have been tested in the same Docker image that is used in
CI.
Also, the `-u` flag has been added to the `set` command so that the script fails on any error. This is useful because so far, CI failed due to `golang:latest-alpine` not being a valid image. This image name was only created because the if-check didn't succeed due to the syntax error.
With the `-u` flag, this would have exited earlier and would have made the issue more obvious as well.
=> test: fix regression test shell issues

lib/extractor/oci-archive/layer.ts, lib/extractor/types.ts, test/system/image-type/__snapshots__/oci-archive.spec.ts.snap, test/system/image-type/oci-archive.spec.ts
According to the spec, the manifests in an image index may also be
references to other index files, and not only image manifests. This fix
adds support for the nested index case.
https://snyksec.atlassian.net/browse/MYC-142
=> fix: support nested index files in OCI images

lib/inputs/python/static.ts, test/lib/analyzer/python-pip-analyzer.spec.ts, test/system/operating-systems/oraclelinux8.2.spec.ts
The site-packages directory can be found in various locations depending
on python version and usage of virtual environment. This fix allows more
flexibility in finding it
=> fix: python site-package location

lib/go-parser/go-binary.ts, lib/go-parser/index.ts, tslint.json
Some CGo-built binaries might not contain a pcln table, as is described in [Building a better Go linker](https://docs.google.com/document/d/1D13QhciikbdLtaI67U6Ble5d_1nsI4befEd6_k1z91U/view):
> For “cgo” binaries, which may make arbitrary use of C libraries, the
Go linker links all of the Go code into a single native object file and then invokes the system linker to produce the final binary.
One example and the reason why we have found this issue is containerd, that is built with CGo enabled.
I do not know how exactly to build a Go binary without a PCLN table, but somehow it must be possible :-)
So far, we have thrown an error and thus exited the scan if the PCLN table was missing in a Go binary, because we did not expect this case to exist. Now that we know it exists, this commit fixes …
=> fix: skip CGo binaries without PCLNTable

.circleci/config.yml
- Upgrade windows orb
- Use a large resource class for slow Windows jest test
This should make the Windows Jest test run faster, and reduce the chance for a timeout from this test and failing the pipeline, which has been driving everyone crazy.
=> chore: bump windows executor

lib/analyzer/image-inspector.ts, test/lib/analyzer/image-inspector.spec.ts, test/windows/plugin.spec.ts
This commit amends the condition used to check against `err.stderr` from the docker daemon, based on the latest response (assume it must have changed), when the manifest for a given image or tag cannot be found. It ensures that the errors is not treated as a generic error and will not fall back to use `snyk-docker-pull` and fail with invalid credentials error when using the docker binary.
https://snyk.zendesk.com/agent/tickets/32820
=> fix: amending condition for 'manifest unknown' errors

lib/analyzer/image-inspector.ts, lib/analyzer/os-release/static.ts, lib/analyzer/static-analyzer.ts, lib/extractor/docker-archive/layer.ts, lib/extractor/layer.ts, lib/extractor/oci-archive/layer.ts, lib/inputs/rpm/static.ts
This commit removes all occurrences of printed errors that are being formatted with `JSON.stringify()`, as that formats the error to an empty object `{}`, which is not helpful.
It also removes calls to `debug` with `error` as the second argument, and embeds them into the string. This is purely to make all our error messages look the same.
=> fix: unify error message formatting

lib/analyzer/package-managers/rpm.ts, lib/inputs/rpm/static.ts, package.json
This commit switches to the new rpm parser that supports modules.
Switches to the new RPM Parser version with an improved interface.
The upcoming changes for redhat required a new API, which was the initial motivation for this PR. I've split up the API changes with the module handling now to get this merged earlier.
=> refactor: use new rpm parser version

lib/sub-process.ts
The Extensible CLI uses an internal proxy/gateway to forward traffic to snyk.io. Some external tools like docker would by default also pass their traffic through the internal proxy. In case of docker this can cause different issues, which is why this PR restores the system proxy configuration before spawning the docker client.
lib/sub-process.ts
HMMR-627
=> fix: Restore system proxy configuration if available

lib/extractor/image.ts, lib/response-builder.ts, lib/static.ts, lib/types.ts, test/lib/extractor/image.spec.ts, test/system/dockerfile-analysis/__snapshots__/dockerfile.spec.ts.snap
Pass the image name with digest via options for Kubernetes Monitor, so we can add that into the imageName facts.
https://snyksec.atlassian.net/browse/RUN-2459
=> RUN-2459 fix: pass image with digest via options for kubernetes monitor

.circleci/config.yml
This commit updates the CircleCI config to use the Slack Orb to send us notifications if any pipeline failures occur on the main branch.
=> chore: use slack orb to notify

.circleci/config.yml
=> chore: pin semantic release

lib/inputs/python/static.ts, test/system/application-scans/python/__snapshots__/pip.spec.ts.snap, test/system/application-scans/python/pip.spec.ts
- adds support for python dist-packages
- [Slack](https://snyk.slack.com/archives/C04HJ3ZD0UC/p1673345207093139)
- ZEN-39783
pip-dist-packages.tar contents:
```terminal
find . -name METADATA
./usr/local/lib/python3.10/dist-packages/rpc.py-0.4.2.dist-info/METADATA
./usr/local/lib/python3.10/dist-packages/Jinja2-3.1.2.dist-info/METADATA
./usr/local/lib/python3.10/dist-packages/six-1.16.0.dist-info/METADATA
./usr/local/lib/python3.10/dist-packages/setuptools-63.2.0.dist-info/METADATA
./usr/local/lib/python3.10/dist-packages/Werkzeug-2.2.2.dist-info/METADATA
./usr/local/lib/python3.10/dist-packages/click-8.1.3.dist-info/METADATA
./usr/local/lib/python3.10/dist-packages/MarkupSafe-2.1.1.dist-info/METADATA
./usr/local/lib/python3.10/dist-packages/wheel-0.37.1.dist-info/METADATA …
```
=> fix: python dist-packages support

lib/analyzer/package-managers/rpm.ts, lib/analyzer/static-analyzer.ts, lib/analyzer/types.ts, lib/dependency-tree/index.ts, lib/facts.ts, lib/response-builder.ts, lib/types.ts, package.json, test/lib/analyzer/package-managers/rpm.spec.ts, test/system/application-scans/__snapshots__/node.spec.ts.snap, test/system/application-scans/python/__snapshots__/poetry.spec.ts.snap, test/system/bugs/__snapshots__/rpm-transitive-dependencies.spec.ts.snap, test/system/flags/__snapshots__/app-vulns.spec.ts.snap, test/system/operating-systems/__snapshots__/centos6.spec.ts.snap, test/system/operating-systems/__snapshots__/centos7.spec.ts.snap, test/system/operating-systems/__snapshots__/oraclelinux8.2.spec.ts.snap, test/system/operating-systems/__snapshots__/sles15.spec.ts.snap, test/system/operating-systems/__snapshots__/ubi8.spec.ts.snap, test/system/operating-systems/ubi8.spec.ts, test/system/package-managers/__snapshots__/rpm.spec.ts.snap, test/system/red-hat-repositories/__snapshots__/red-hat-repositories.spec.ts.snap, test/windows/__snapshots__/application-scans.spec.ts.snap
=> feat: RedHat Modules & PURLs

lib/docker.ts, package-lock.json, package.json
This PR adds support for analyzing OCI images without a local Docker installation. This PR is little more than a version bump to the libraries `snyk-docker-pull` and `docker-registry-v2-client`; the new behaviour is triggered by passing additional content types to avoid being breaking.
Ensure non-OCI and OCI images are both correctly analyzed.
=> feat(oci): support oci images without local docker installation

lib/extractor/index.ts, test/lib/extractor/extractor.spec.ts
Attempt to extract oci archive even if the use specified that the archive is a docker archive.
The user of the plugin doesn't necessarily know the archive type. 
Changed to always attempt to use the OCI extractor if the Docker extractor failed.
=> fix: fallback to other archive extractor in case of failure

.circleci/config.yml
As part of the decommissioning of the `snyksec` GH account, a new `team-lumos` context has been created to allow team specific control over service accounts; namely the use of `GH_TOKEN` and `NPM_TOKEN` env vars used in nodejs install and release jobs.
The new context has been added, in addition, to existing contexts, where the `GH_TOKEN` is required. Also changed the context from `snyk-lumos` to `team-lumos` for Snyk tests as it makes more sense to manage a single context for our pipelines.
- [Jira Ticket](https://snyksec.atlassian.net/browse/LUM-280)
=> chore: uses team-lumos context in build pipelines

components/common.yaml, lib/types.ts
- chore: alphabetically sort fact types
- chore: document openapi missing fact types
=> chore: add openapi spec fact types

lib/analyzer/package-managers/apt.ts, lib/analyzer/types.ts, lib/dependency-tree/index.ts, package-lock.json, package.json, test/lib/analyzer/package-managers/apt.spec.ts, test/system/app-os/__snapshots__/globs.spec.ts.snap, test/system/dockerfile-analysis/__snapshots__/dockerfile.spec.ts.snap, test/system/image-type/__snapshots__/compressed-archive.spec.ts.snap, test/system/image-type/__snapshots__/docker-archive.spec.ts.snap, test/system/key-binaries-hashes/__snapshots__/hashes.spec.ts.snap, test/system/operating-systems/__snapshots__/debian9.spec.ts.snap, test/system/operating-systems/__snapshots__/distroless.spec.ts.snap, test/system/operating-systems/__snapshots__/ubi8.spec.ts.snap, test/system/package-managers/__snapshots__/deb.spec.ts.snap, test/system/platforms/__snapshots__/amd.spec.ts.snap, test/system/red-hat-repositories/__snapshots__/red-hat-repositories.spec.ts.snap
The source version of a package may not be the same as the package version, which is why we should track them whenever they differ. This change ensures we populate an "upstream" qualifier (similarly to how Syft does this) with the source name and version. "upstream" is a non-standard qualifier, but matches Syft for consistency.
Tracking the source version is important because Snyk's vuln intel on Debian is based on the source version not the binary version. Some packages like postgres-client have differing binary and source versions, which results in reporting false positives once the wrong vulnerable version range is matched.
=> feat: include upstream/source name and version in purl

lib/scan.ts, lib/types.ts, test/system/plugin-option.spec.ts
Passing digests scan option to docker and oci archive scanning to enrich imageName fact type.
* lib/scan.ts
* lib/types.ts
scan an OCI/docker archive by providing both `imageNameAndTag` and `digests` scan options.
This implementation would enable Docker Registry Agent to pass both manifest and index digest information to enrich imageName fact type in order for Container Image Service to consume this data.
=> feat: passing manifest and index digest to archive scanning

.circleci/config.yml, lib/analyzer/image-inspector.ts, lib/analyzer/os-release/static.ts, lib/analyzer/static-analyzer.ts, lib/extractor/docker-archive/layer.ts, lib/extractor/layer.ts, lib/extractor/oci-archive/layer.ts, lib/go-parser/index.ts, lib/inputs/rpm/static.ts, package-lock.json, package.json
**chore: update shescape**
When debugging issues within our Windows CI, I've noticed that
`shescape` has a couple of bug fixes related to Windows. Although it
turned out that `shescape` is not the issue here, I'm keeping that
update in just for good measure.
**fix: error handling when pulling images with pull library**
So far, we've only handled errors when pulling with the Docker CLI. With
the Docker CLI, we've "translated" errors to make them more helpful.
The Windows tests have now started to fail because of a broken Docker
installation, as we then fell back to the `snyk-docker-pull` library,
which didn't have that error translation.
This commit fixes that, and applies that error handling to both the CLI
errors as well as errors from snyk-docker-pull.
**fix: error messages in debugs** …
=> fix docker pull issues

lib/analyzer/image-inspector.ts
The test asserts that cleanup has worked and the directory has been removed. However, because `rmdir` is asynchronous (internally, it's not a Promise), sometimes the directory was still there when our assertions ran.
Using `rmdirSync` should fix these issues and make us wait for the directory to be deleted.
The impact to runtime should be negligible, due to the fact that we delete the image-archive *before* the `rmdir` call with an `unlinkSync` already.
=> test: fix test flake by using rmdirSync

lib/dependency-tree/index.ts, lib/types.ts, test/lib/dependency-tree/index.spec.ts, test/system/app-os/__snapshots__/globs.spec.ts.snap, test/system/dockerfile-analysis/__snapshots__/dockerfile.spec.ts.snap, test/system/image-type/__snapshots__/compressed-archive.spec.ts.snap, test/system/image-type/__snapshots__/docker-archive.spec.ts.snap, test/system/index.spec.ts, test/system/key-binaries-hashes/__snapshots__/hashes.spec.ts.snap, test/system/operating-systems/__snapshots__/debian9.spec.ts.snap, test/system/package-managers/__snapshots__/deb.spec.ts.snap, test/system/platforms/__snapshots__/amd.spec.ts.snap, test/system/platforms/__snapshots__/arm.spec.ts.snap, test/system/red-hat-repositories/__snapshots__/red-hat-repositories.spec.ts.snap
Frequently found dependencies can cause many upgrade paths to be generated which creates a bad UX when issue grouping is applied in the UI. Grouping these packages under a "fake" package, `meta-common-packages` solved this but broke the upgradable logic for Linux package managers, which need direct dependencies to be upgradable.
This commit attaches frequently found dependencies directly to the tree root for Linux package managers so the upgrade path shows the package as a direct dependency and becomes upgradable.
> Updated test snapshots to take account of `meta-common-packages` package no longer being present in scan results.
[SUP-1367](https://snyksec.atlassian.net/browse/SUP-1637)
[SUP-1367]: https://snyksec.atlassian.net/browse/SUP-1367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
=> fix: removes meta-common-packages generation for Linux package managers

.gitignore, lib/analyzer/image-inspector.ts, test/lib/analyzer/image-inspector.spec.ts
Fixes the case when the docker daemon is unavailable, and both the image digest and tag are present.
The reviewer can start with the newly added unit test to better understand the issue.
Snyk container scanning fails when the docker daemon is unavailable, and both the image tag and digest are passed. This is because of a bug in the code that extracts the image repository from the provided target image argument.
=> fix: correctly handle tag and digest

.circleci/config.yml, package.json
Tests are unstable and failing with timeouts. Will remove the step and migrate the tests to jest in follow PR
Tap windows tests are unstable and failing with timeouts and blocking the pipeline. Will remove the step and migrate the tests to jest in follow PR.
- Also added fix version to `setup_remote_docker` as the new version pulled (`24.0.6`) causing one test to fail.
=> fix: remove tap windows tests step [LUM-739]

lib/dockerfile/index.ts, test/lib/dockerfile.spec.ts
Add "parse dockerfile" functionality.
This functionality should allow clients of `snyk-docker-plugin` to not consume `dockerfile-ast` dep (i.e. `docker-deps`).
=> feat: add "parse dockerfile" functionality

lib/dockerfile/instruction-parser.ts, test/lib/dockerfile/index.spec.ts
When parsing a multistage Dockerfile the last resolved base image was not getting "reset" when a subsequent stage is not resolvable; this results in an incorrect base image being returned.
The added test cases show examples of Dockerfiles that were previously being incorrectly parsed. We previously tested that non resolvable args were handled but we had no tests to check multi-stage builds where some stages were resolvable and some not. There was also a bug with aliases and not checking that an alias of alias was resolvable.
We now look for unresolved variables in the stage, then look for and attempt to resolve any aliases, and "reset" the last known stage if any of the above checks result in an unresolvable base image name for the stage. We only save the base image name after all checks …
=> fix: resets last base image in multistage build when not resolveable

test/system/app-os/globs.spec.ts, test/system/bugs/image-layers.spec.ts, test/system/operating-systems/alpine3.7.spec.ts, test/system/operating-systems/busybox1.32.spec.ts, test/system/operating-systems/centos6.spec.ts, test/system/operating-systems/centos7.spec.ts, test/system/operating-systems/debian9.spec.ts, test/system/operating-systems/distroless.spec.ts, test/system/operating-systems/oraclelinux8.2.spec.ts, test/system/operating-systems/scratch.spec.ts, test/system/operating-systems/sles15.spec.ts, test/system/operating-systems/ubi8.spec.ts, test/system/package-managers/apk.spec.ts, test/system/package-managers/deb.spec.ts, test/system/package-managers/rpm.spec.ts, test/system/platforms/amd.spec.ts, test/system/platforms/arm.spec.ts, test/system/platforms/ppc64le.spec.ts, tslint.json
Remove empty catch statements from the code (as they don't work and actually catch the error which cause to tests failures and instability).
Also disable the `no-console` rule to be able to log the error in case of catch, [as recommended for Node.js](https://eslint.org/docs/latest/rules/no-console#when-not-to-use-it).
=> fix: remove empty catch statements [LUM-746]

lib/python-parser/metadata-parser.ts, test/unit/python-metadata-parser.spec.ts
For most python packages, we coerce the version to a valid semver format. This caused a false positive with versions that are similar to semver, but have an additional identifier, such as opencv-python: 4.8.1.78.
This commit adds support for such versions by not coercing them.
Scan a docker image with a requirements.txt file that contains `opencv-python==4.8.1.78` (and run a pip install).
=> fix: added support for semver-like versions for python dependencies.

package-lock.json, package.json
Upgrading packageurl-js will break the way dep-graphs are currently generated. This PR keeps it at an older version.
=> fix: keep packageurl-js at an older version

components/common.yaml, lib/extractor/oci-distribution-metadata.ts, lib/facts.ts, lib/response-builder.ts, lib/static.ts, lib/types.ts, package-lock.json, package.json, test/lib/extractor/oci-distribution-metadata.spec.ts
This PR adds the `ociDistributionMetadata` fact to scan results _provided_ that:
- `manifestDigest` is provided - without it, we cannot determine whether a digest in the image name is an index or a manifest
- An image identifier is present in the `imageNameAndTag` option
- Jira ticket: https://snyksec.atlassian.net/browse/OI-37
=> feat: add oci distribution metadata fact [OI-37]

lib/extractor/oci-distribution-metadata.ts, lib/static.ts, test/lib/extractor/oci-distribution-metadata.spec.ts
This PR removes the `platform` field from the OCI Distribution Metadata fact; after some discussion it was decided that `platform` is not a property of OCI distribution, but just of the image.
=> feat: remove platform from oci distribution metadata

lib/analyzer/applications/java.ts, lib/buffer-utils.ts, test/lib/buffer-utils.spec.ts
Adds large file support to `bufferToSha1` method.
The `bufferToSha1` method was failing as the `update` method of the `Crypto.Hash` object uses `Buffer.alloc` which has a limitation of 2G. Any JARs bigger than this would cause a `RangeError` in `Node`.
This fix uses the stream interface of `Crypto.Hash` to stream data for large files in order to generate the Sha1 digest.
Scan any container with a Maven project that contains one or more JAR over 2G in size.
https://snyksec.atlassian.net/browse/SUP-1997
=> fix: adds large file support to bufferToSha1 method

lib/extractor/index.ts, lib/extractor/layer.ts, test/system/deleted-files.spec.ts
When a file or folder is deleted, an entry that starts with .wh is created. Up until now, Snyk detected files that were deleted, but not folders.
This change adds support for deleted folders by checking whether a file path starts with the path of the deleted folder. Meaning if we know that "/app/dependencies" was deleted, then a file path like "/app/dependencies/jar/library.jar" will be marked as deleted as well.
To test this change, create an image from a dockerfile that:
* creates a folder
* downloads / copies a file that is recognized by Snyk (like `.jar` or `package-lock.json`) to that folder
* deletes the folder
=> fix: add support for deleted folders

lib/analyzer/package-managers/apt.ts, lib/analyzer/package-managers/rpm.ts, lib/analyzer/static-analyzer.ts, test/system/app-os/__snapshots__/globs.spec.ts.snap, test/system/application-scans/__snapshots__/node.spec.ts.snap, test/system/bugs/__snapshots__/rpm-transitive-dependencies.spec.ts.snap, test/system/dockerfile-analysis/__snapshots__/dockerfile.spec.ts.snap, test/system/flags/__snapshots__/app-vulns.spec.ts.snap, test/system/image-type/__snapshots__/compressed-archive.spec.ts.snap, test/system/image-type/__snapshots__/docker-archive.spec.ts.snap, test/system/key-binaries-hashes/__snapshots__/hashes.spec.ts.snap, test/system/operating-systems/__snapshots__/centos6.spec.ts.snap, test/system/operating-systems/__snapshots__/centos7.spec.ts.snap, test/system/operating-systems/__snapshots__/debian9.spec.ts.snap, test/system/operating-systems/__snapshots__/distroless.spec.ts.snap, test/system/operating-systems/__snapshots__/oraclelinux8.2.spec.ts.snap, test/system/operating-systems/__snapshots__/sles15.spec.ts.snap, test/system/operating-systems/__snapshots__/ubi8.spec.ts.snap, test/system/package-managers/__snapshots__/deb.spec.ts.snap, test/system/package-managers/__snapshots__/rpm.spec.ts.snap, test/system/platforms/__snapshots__/amd.spec.ts.snap, test/system/red-hat-repositories/__snapshots__/red-hat-repositories.spec.ts.snap, test/windows/__snapshots__/application-scans.spec.ts.snap
Fixes purl generation for `apt` and `rpm` packages. The fix entails:
- Adding the vendor name as a namespace in PURLs
- For debian, mapping the version number to a corresponding codename
- Adding the `distro` qualifier in PURLs
=> feat: fix purl generation for container

package-lock.json, package.json
After the release of the [npm support scan of npm projects without lockfiles ](https://github.com/snyk/snyk-docker-plugin/pull/578/files), one of the required dependencies wrongly ended up as a `devDependency`.
This PR fixes the `snyk-resolve-deps` dependency type.
=> fix: nodejs-parser dependency type

lib/analyzer/applications/python/pip.ts, lib/python-parser/common.ts, test/fixtures/python/non-semver-versions/requirements.txt, test/fixtures/python/non-semver-versions/site-packages/other.py-7.4.2.15.dist-info/METADATA, test/fixtures/python/non-semver-versions/site-packages/other.py-7.4.2.3.dist-info/METADATA, test/lib/analyzer/python-pip-analyzer.spec.ts, test/unit/python-common.spec.ts
This fixes an issue where an exception would occur when a python dependency had a version that did not conform to semver specs, such as 1.18.3.9
=> fix: use custom version compare function to support multiple version string compare groups

lib/analyzer/applications/node-modules-utils.ts, lib/analyzer/applications/node.ts, lib/analyzer/applications/types.ts, lib/inputs/node/static.ts, test/lib/docker.spec.ts, test/system/application-scans/__snapshots__/node.spec.ts.snap, test/system/application-scans/node.spec.ts, test/system/operating-systems/__snapshots__/ubi8.spec.ts.snap, test/system/registry-authentication/__snapshots__/username-password.spec.ts.snap
Co-authored-by: danlucian lucian.rosu@snyk.io
With the release of [v6.12.0](https://github.com/snyk/snyk-docker-plugin/releases/tag/v6.12.0) of the docker cli plugin we added support for scanning `npm` projects without manifest/lockfiles. `npm` ecosystem has both global and local scoped dependencies and, to avoid false positives, we decided to ignore a [set of folders](https://github.com/snyk/snyk-docker-plugin/compare/v6.11.2...v6.12.0#diff-578f2462189d520724e9a93b42832b47b088ae4315005902a9abbcc552215250R7) from the containers at that time of release. We realised that the accuracy of the cli was impacted by that change and we decided to remove the ignoring of the `/usr/` and `/opt` folders. 
This PR aims to solve the issue mentioned above and slightly refactor the way we handle node …
=> fix: remove ignored paths when discovering npm manifest files UNIFY-216

lib/analyzer/applications/java.ts, lib/buffer-utils.ts, test/lib/buffer-utils.spec.ts
Because we currently decompress .jar files using adm-zip that does not support streaming,
we load the .jar file in memory using the Buffer class. Due to the current design,
we can read .jar files of up to buffer.constants.MAX_LENGTH. On 32-bit architectures, this value
currently is 230 - 1 (about 1 GiB). On 64-bit architectures, this value currently is 232 (about 4 GiB).
Refactors `buffertoSha1` function to support hashing of large buffers by reading the buffer in chunks using a `Readable`stream. This fixes the case the crypto module is throwing `The RangeError: data is too long`because it cannot handle the size of data passed to it in one go. However due to the current design, we support hasing .jar files of up to `buffer.constants.MAX_LENGTH`.
=> fix: compute sha1 on .jar files of size up to buffer.constants.MAX_LENGTH

lib/extractor/index.ts, lib/extractor/oci-archive/layer.ts, test/system/platforms/arm.spec.ts
The previous implementation of the snyk-docker-plugin ecplicitly required the --platform parameter to be passed in order to scan the correct architecture of the image. If --platform was not provided, it would be defaulted to "linux/amd64" and threw an "invalid OCI Archive" error if the platform was different than "linux/amd64".
The new implementation makes it so that it auto-detects the platform information from config files when --platform in missing, if possible, or default it to "linux/amd64" if not possible.
lib/extractor/oci-archive/layer.ts
With the fix:
```
SNYK_API=https://app.snyk.io/api/v1 node index.js container monitor arm64v8/debian:latest
Monitoring arm64v8/debian:latest (docker-image|arm64v8/debian)...
Explore this snapshot at …
```
=> fix: detect platform from image config file UNIFY-253

lib/extractor/index.ts, lib/extractor/layer.ts, test/system/deleted-files.spec.ts
The customer noticed that we are still reporting vulnerabilities from jars that were deleted.
The issue was that in the extracted layers we could find multiple additions of the exact same file. Docker allows the addition of exactly the same file in exaclty the same path multiple times. We parse layers in reverse chronological order, so encountering removals first means those files are 100% removed. For clarifying, removals are marked with ".wh.".
Before this change, we would only take into account a removal for the first instance of that exact same file in the following layers. 
"Getting into" a container created using this image (using docker debug) the existence of these files can be checked. No matter in how many layers we added that one exact same file, one remove is enough to make …
=> fix: correctly detect files from removed layers UNIFY-243

lib/analyzer/applications/node-modules-utils.ts, lib/analyzer/applications/node.ts, test/system/application-scans/node.spec.ts
Refactoring the groupFilesByDirectory to handle:
- filtering npm/yarn/pnpm cache files
Compute node_modules parent directory using regexes instead of substring searching.
=> fix: ignore npm cache directories UNIFY-264

tsconfig.json
From es2017 to es2018.
Noticed that regex capture groups are not fully supported in es2017.
TS(1503) static analysis warning.
=> fix: upgrade Typescript target

lib/inputs/redHat/static.ts, test/system/operating-systems/__snapshots__/ubi9.spec.ts.snap, test/system/operating-systems/ubi9.spec.ts
When content_sets is not present is absent from the redhat-content-manifests we try to cast to string [] an undefined value.
https://app.datadoghq.com/logs?query=%22cli%20analytics%22%20%40polaris.instance%3Apolaris-prod-mt-gcp-1%20%2A%3Aintermediate%2A&agg_m=count&agg_m_source=base&agg_q=%40originalError.message&agg_q_source=base&agg_t=count&cols=host%2Cservice%2C%40originalError.message%2C%40name%2C%40data&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&top_n=30&top_o=top&viz=toplist&x_missing=true&from_ts=1730318170926&to_ts=1731614170926&live=true
=> fix: redhat-content-manifests content sets parsing UNIFY-387

package-lock.json, package.json
use `npm audit fix` to simplify overrides for security vulns
=> chore: simplify npm package overrides

lib/analyzer/applications/node-modules-utils.ts, lib/analyzer/applications/node.ts, lib/analyzer/static-analyzer.ts, lib/types.ts, test/system/application-scans/__snapshots__/node.spec.ts.snap, test/system/application-scans/node.spec.ts
Before [v6.12.0](https://github.com/snyk/snyk-docker-plugin/releases/tag/v6.12.0), the docker cli plugin was able to scan `npm` projects only when [strict `package.json` and `package-lock.json` pairs](https://github.com/snyk/snyk-docker-plugin/blob/ac707fdb49a29406e61d04a26ddd6f3c91b626a1/lib/analyzer/applications/node.ts#L88-L104) of files were identified within container images. The pair of files [had to be outside](https://github.com/snyk/snyk-docker-plugin/blob/ac707fdb49a29406e61d04a26ddd6f3c91b626a1/lib/inputs/node/static.ts#L12) of a `node_modules` folder’s context in order to avoid creating projects out of the dependencies. Scanning container images that had the manifests/lockfiles removed was not possible and customer needs were created to remove that constraint.
The scanning of …
=> feat: add option to disable the node_modules scan for node.js images

lib/index.ts, lib/scan.ts, test/system/application-scans/gomodules.spec.ts, test/system/application-scans/node.spec.ts, test/system/application-scans/python/pip.spec.ts
Exposes a new function aside the existing `scan` function which collects the application files from within an image.
- Follow the existing `scan` method and see it's current logic did not break
- Review the new `exposeContent` method and make sure it does collect the intended data
Install locally using `file:../snyk-docker-plugin` and add a call to the function using a known image.
This is part of the Runtime team efforts to collect application files from images. See more details here - https://snyksec.atlassian.net/wiki/spaces/RD/pages/2688188638/Code+lineage+-+collect+file+hierarchy+from+container+registry
https://snyksec.atlassian.net/browse/RNTM-825
=> Expose image content extraction

package-lock.json, package.json
Bumps nodejs-lockfile-parser, mainly to fix a yarn bug in out of sync resolutions erroring: https://github.com/snyk/nodejs-lockfile-parser/pull/267.
Other changes included with this update: https://github.com/snyk/nodejs-lockfile-parser/releases - mostly pnpm bugfixes + an npm bugfix that only works 'under a feature flag' (https://github.com/snyk/nodejs-lockfile-parser/commit/6d81596b4248381bd5eedf6a5199253c38988f79). These should not affect the lockfile parser functionality in this repo.
This PR https://github.com/snyk/nodejs-lockfile-parser/pull/267.
With a yarn project with manifest files `yarn.lock` and `package.json` from the lockfile-parser test: https://github.com/snyk/nodejs-lockfile-parser/pull/267/files#diff-6df26e787f44dccd9215fd24d8d1624c300d015bab261b87568c3b7793a1f62f. 
A …
=> fix: bump nodejs-lockfile-parser

lib/analyzer/static-analyzer.ts, lib/inputs/rpm/static.ts, package-lock.json, package.json, test/system/operating-systems/__snapshots__/sles15.spec.ts.snap, test/system/operating-systems/sles15.spec.ts
Adds support for NDB Berkley Rpm Database. Starting with SLE 15.3, SUSE adopted the NDB format. The database file can be found in: /usr/lib/sysimage/rpm/Packages.db and is a faster hash-based layout of the RPM DB compared to the old Berkeley DB (BTree) used in SLE 15.2 or older.
` snyk container test registry.suse.com/suse/sle15:15.6`
https://snyksec.atlassian.net/browse/CN-72
=> feat: add support for NDB RPM database

package-lock.json, package.json
This PR adds the dev dependency `@types/minimatch`. Typescript compilation fails without this dependency.
Prior to this change, running `npm ci && npm run build` from within a docker container fails with:
```
> build
> tsc
added 927 packages, and audited 928 packages in 12s
119 packages are looking for funding
run `npm fund` for details
3 vulnerabilities (2 low, 1 moderate)
To address issues that do not require attention, run:
npm audit fix
To address all issues, run:
npm audit fix --force
Run `npm audit` for details.
npm notice
npm notice New major version of npm available! 10.8.2 -> 11.4.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.4.2
npm notice To update run: npm install -g npm@11.4.2
npm notice
> build
> tsc
lib/inputs/file-pattern/static.ts:15:23 - error …
```
=> chore: add required @types/minimatch dev dependency

lib/analyzer/image-inspector.ts, lib/sub-process.ts, package-lock.json, package.json, test/system/plugin.spec.ts
Updates the sub-process execution logic to remove the default shells used in spawning the child processes and execute the docker binaries directly without relying on a shell. This eliminates the need for a specific shell binary (like /bin/bash or /bin/sh) to be present, making the function portable on a broader range of operating systems and minimal distributions like alpine that default to /bin/sh. 
Adds a test to validate that the scanner completes on locally available images.
=> fix: improve subprocess spawning portability

lib/go-parser/pclntab.ts, test/unit/go-binaries.spec.ts
Go version 1.25 released last week, and it's breaking the pipeline
=> fix: go regression test fix

test/lib/analyzer/os-release-detector.spec.ts
Added some tests to improve the test coverage for snyk-docker-plugin. `os-release` specifically for this PR
Before:
After:
=> chore: tests for os-release

test/system/package-managers/__snapshots__/rpm.spec.ts.snap, test/system/package-managers/rpm.spec.ts
quay.io deletes previous versions of images as soon as they push a new version. This PR fixes the breaking tests, as they're pointing to now outdated images
We should redo the tests to use a different image that won't get removed every month, but in the meantime this will fix the faililng tests
=> fix: update old quay images

lib/analyzer/image-inspector.ts, lib/analyzer/static-analyzer.ts, lib/inputs/java/static.ts, lib/types.ts, test/lib/inputs/java-static.spec.ts, test/system/flags/include-system-jars.spec.ts
This PR adds a parameter to support jars under the usr/lib directory
There is a new parameter "include-system-jars" that should control this feature.  It should default to off.
test with include-system-jars=false and then compare to include-system-jars=true
Make sure you are using a container image with jar files in the usr/lib file to properly evaluate
CN-280
=> feat: [CN-280] Add parameter to support usr/lib jar files

lib/analyzer/image-inspector.ts, lib/analyzer/types.ts, lib/docker.ts, lib/scan.ts, lib/utils.ts, test/lib/analyzer/image-inspector.spec.ts, test/lib/utils.spec.ts
Migrate docker inspect calls to be direct API calls to the docker daemon instead of subprocess calls that use the docker CLI. This is a cleaner approach and mitigates various potential failure scenarios that arise from the subprocess call.
https://snyksec.atlassian.net/browse/CN-222
=> feat: migrate inspect to direct API call

package.json, test/fixtures/centos-shas.ts, test/system/package-managers/__snapshots__/rpm.spec.ts.snap, test/system/package-managers/rpm.spec.ts, update_centos_shas.sh
StreamOS 9 and StreamOS 10 tests constantly fail in snyk-docker-plugin.
This is because Redhat’s [quay.io](http://quay.io/) repo does not store old shas once an image is updated. So every time they update the image, the hardcoded sha values need to be updated
To alleviate this, I’ve written a shell script to update the shas and update the test snapshot
So if these fail in the future, run:
`npm run update-quay-tests`
=> fix: update quay tests and add a script to update them
