- package.json
Reverts snyk/snyk-docker-plugin#34
> Revert "chore: upgrade semantic-release"

- .eslintrc
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- Contributor-Agreement.md
- appveyor.yml
- lib/fetch-snyk-docker-analyzer.js
- lib/index.js
- lib/sub-process.js
- package.json
- test/system.test.js
* Update `semantic-release` to `^15`
* Replace `jscs` with `eslint`
* Add contributing agreement
> chore: update release process

- lib/index.ts
- test/system/system.test.ts
This patch improves the image name parsing to account for hosts with ports as well as multiple '/' in the image name.
Note that while a similar end result could be achieved with a regex, the resulting code would likely be too terse for anyone without a reasonable grasp of the docker ecosystem (tag formats etc) to understand quickly. Lets stick to verbose and readable, as it is not a performance concern in this case.
Big thanks to @Limess for #44 which was most of the work involved in this patch and for spotting the bug in the first place.
> fix: Correctly parse host with port

- lib/docker-file.ts
- package-lock.json
- package.json
- test/fixtures/dockerfiles/with-args/Dockerfile
- test/lib/docker-file.test.ts
- tsconfig.json
We were not previously taking ARG into account when parsing FROM
instructions; this patch pulls in an external lib to parse dockerfiles
> fix: dockerfile parsing when using ARG with FROM

- lib/analyzer/binaries-analyzer.ts
- lib/analyzer/index.ts
- test/lib/analyzer/binaries-analyzer.test.ts
We want to remove duplication of vulnerabilities for the case
that node installed by a package manager.
> feat: don't fetch node binaries if they are installed by package manager

- lib/analyzer/binaries-analyzer.ts
- lib/analyzer/binary-version-extractors/node.ts
- lib/analyzer/binary-version-extractors/openjdk-jre.ts
- test/lib/analyzer/binaries-analyzer.test.ts
- test/lib/analyzer/index.test.ts
Adds support for detecting `openjdk-jre` binary.
Test `snyk test --docker openjdk:latest`.
> feat: support openjdk-jre

- lib/index.ts
export `dockerFile` for `registry` to use `analyseDockerfile` in order to validate Dockerfile contents before saving its details to DB.
https://snyksec.atlassian.net/browse/DC-169
> feat: export dockerfile for registry to validate dockerfile

- lib/inputs/rpm/static.ts
fixing a typo / copy-paste error.
I assume the meaning was for rpmDb and not apk, since the context is RPM static scanning.
> chore: typo / copy-paste error

- lib/analyzer/docker-analyzer.ts
Fixes a typo (`binarisAnalysis` -> `binariesAnalysis`)
N/A
N/A
N/A
N/A
N/A
N/A
> chore: fix minor typo

- lib/index.ts
> chore: removing unused parameter

- lib/experimental.ts
- test/system/static.test.ts
Pulls distroless images in case they are not pulled
> feat: distroless pull image if needed

- .circleci/config.yml
- appveyor.yml
> Feat: change tests to node 12

- .circleci/config.yml
make semantic-release work with node 8
> chore: make semantic-release work with node 8

- lib/types.ts
improved types for plugin response
> chore: improved types for plugin response

- lib/analyzer/applications/index.ts
- lib/analyzer/applications/node.ts
- lib/analyzer/applications/types.ts
- lib/analyzer/static-analyzer.ts
- lib/analyzer/types.ts
- lib/inputs/node/static.ts
- lib/response-builder.ts
- lib/static.ts
- lib/types.ts
- package.json
- test/fixtures/analysis-results/npm.json
- test/fixtures/analysis-results/yarn.json
- test/system/application-scans.test.ts
- test/system/static.test.ts
- test/system/system.test.ts
Introduces Node application dependencies scanning as part of static scanning.
Review commit by commit 🙏 
[Jira ticket RUN-880](https://snyksec.atlassian.net/browse/RUN-880)
> feat: scan Node application dependencies in static scanning

- package.json
- test/lib/analyzer/apk-analyzer.test.ts
- test/lib/analyzer/apt-analyzer.test.ts
- test/lib/analyzer/binaries-analyzer.test.ts
- test/lib/analyzer/image-inspector.test.ts
- test/lib/analyzer/index.test.ts
- test/lib/analyzer/os-release-detector.test.ts
- test/lib/analyzer/rpm-analyzer.test.ts
- test/lib/docker-file.test.ts
- test/lib/docker.test.ts
- test/lib/extractor/image.test.ts
- test/lib/extractor/index.test.ts
- test/lib/image-type.test.ts
- test/lib/instruction-parser.test.ts
- test/lib/ls-utils.test.ts
- test/lib/stream-utils.test.ts
- test/system/application-scans.test.ts
- test/system/experimental.test.ts
- test/system/rpm.test.ts
- test/system/static.test.ts
- test/system/system.test.ts
upgrade tap to remove the need to have shebang at the beginning of test files and making them executable
https://snyksec.atlassian.net/browse/RUN-899
> [RUN-899] chore: test files do not need to be executable and start with shebang

- lib/index.ts
- [ X] Ready for review
- [ X] Follows CONTRIBUTING rules
- [ X] Reviewed by Snyk internal team
export missing interfaces
> fix: export missing interfaces

- .circleci/config.yml
Runs tests on merge to master, before releasing a new version
https://snyksec.atlassian.net/browse/RUN-931
> [RUN-931] chore: run tests on merge to master

- .circleci/config.yml
- .circleci/slack-notify-success.sh
sends notifications to Slack when successful publish happens
https://snyksec.atlassian.net/browse/RUN-920
> [RUN-920] chore: send slack notification on successful publish

- .circleci/slack-notify-success.sh
change successful slack message content
> chore: change successful slack message content

- lib/docker.ts
- lib/inputs/binaries/docker/node.ts
- lib/inputs/binaries/docker/openjdk-jre.ts
- test/lib/analyzer/binaries-analyzer.test.ts
1. fix tests, which haven't actually tested errors at all in key binaries
2. extended the errors to a bit wider options
> fix: more general key binary error handling

- package.json
The parser carries the fix in a transient dependency (event-loop-spinner).
The parser also carries a breaking change: Node.js 8 as a minimum dependency.
> feat: upgrade rpm-parser to reduce event loop waits

- lib/analyzer/static-analyzer.ts
- lib/experimental.ts
- lib/image-type.ts
- test/lib/image-type.test.ts
- test/system/experimental.test.ts
Adding OCI image scanning to the experimental flow.
Commit by commit please :-) 
[RUN-952](https://snyksec.atlassian.net/browse/RUN-952)
> Add OCI support in experimental flow

- lib/analyzer/package-managers/apk.ts
- test/fixtures/os/alpine_2_6_6/analyzer-expect.json
- test/system/system.test.ts
Reverts change to apk packages' names.
> fix: add origin to apk packages

- lib/analyzer/package-managers/apk.ts
- test/fixtures/os/alpine_2_6_6/analyzer-expect.json
- test/system/system.test.ts
add origin to apk packages to improve vuln querying
https://snyksec.atlassian.net/browse/RUN-987
> [RUN-987] fix: add origin to apk packages to improve vuln querying

- .circleci/config.yml
It requires the pipeline steps Lint, Build and Tests for Release Github step.
It includes only the required options in the pipeline workflow.
- [RUN-1061](https://snyksec.atlassian.net/browse/RUN-1061)
> chore: enforce release after tests, lint and build

- lib/analyzer/os-release/docker.ts
- lib/analyzer/os-release/static.ts
- lib/inputs/rpm/static.ts
- test/fixtures/os/sles_15/fs/etc/os-release
- test/lib/analyzer/os-release-detector.test.ts
- test/system/static.test.ts
> feat: add suse and opensuse support

- test/lib/docker.test.ts
fixes a test flakiness
https://snyksec.atlassian.net/browse/RUN-1188
> [RUN-1188] test: fix flake in loading image tar

- test/lib/analyzer/image-inspector.test.ts
- test/lib/docker.test.ts
fix flake in loading image tar
> test: fix flake in loading image tar

- lib/analyzer/applications/java.ts
- lib/analyzer/applications/node.ts
- lib/facts.ts
- lib/index.ts
- lib/response-builder.ts
- test/lib/facts.spec.ts
Ensure our Facts are strongly typed to prevent mistakes in use. We are also exporting them so that users of the plugin can also correctly work with the expected interfaces.
> fix: add TypeScript types for any scanned Facts

- package.json
Memory and speed optimization with new dep graph lib version
> feat: memory and speed optimization with new dep graph lib version

- .github/CODEOWNERS
Update codeowners to team Capsule
> chore: Update codeowners to team Capsule

- package.json
Upgrade lib `dockerfile-ast` from `0.0.30` to `0.1.0` version.
> fix: upgrade lib version

- package.json
Use the most recent `snyk-nodejs-lockfile-parser` which is been modified to reduce lodash exposure.
https://snyk.slack.com/archives/C01MDU3UL59/p1612973794033300
> Use latest snyk-nodejs-lockfile-parser

- lib/analyzer/os-release/static.ts
- package.json
This was previously logging a console message because the wrong `debug` function was used.
> fix: use the correct debug package to log errors

- package.json
> fix: Update vulnerable dependency

- package.json
Updates to https://github.com/snyk/nodejs-lockfile-parser/releases/tag/v1.32.1 to fix transitive vulns
> fix: Update another vulnerable dependency

- package.json
update library dockerfile-ast from 0.2.0 to 0.2.1
> fix: update library dockerfile-ast from 0.2.0 to 0.2.1

- package.json
Update vulnerable package to fix the vulnerability
https://github.com/snyk/nodejs-lockfile-parser/pull/116
> fix: update vulnerable package

- lib/facts.ts
- lib/types.ts
Adds an image size (bytes) fact
> feat: image size fact

- package.json
Update snyk-docker-pull library with a bug fix for 'Unexpected end of data' error we see quite a lot
> fix: upgrade docker pull lib with bug fix

- lib/analyzer/types.ts
We moved from dynamic to static scanning a while back. I guess this is a leftover that wasn't deleted.
> chore: remove unused type

- lib/facts.ts
- lib/types.ts
- test/lib/facts.spec.ts
- [x ] Follows CONTRIBUTING rules
- [x ] Reviewed by Snyk internal team
Add `sysdigLoadedPackages` Fact to support runtime data
Sysdig integration data introduce new fact type
https://snyksec.atlassian.net/browse/RUN-2004
> feat: add runtime pkg fact type

- lib/facts.ts
- lib/types.ts
- test/lib/facts.spec.ts
> fix: rename loaded packages fact

- package.json
Remove vuln in nodejs-lockfile-parser
> fix: remove vuln in nodejs-lockfile-parser

- test/system/application-scans/__snapshots__/gomodules.spec.ts.snap
- test/system/application-scans/gomodules.spec.ts
The test was not checking the right expectation and the Jest snapshot was wrong (it was producing a promise).
> test: add missing "await" in gomodules test

- lib/analyzer/applications/java.ts
- package.json
Avoids using "any" in the code and makes it easier to understand what the available properties and functions are.
> fix: add "adm-zip" typescript types

- .github/CODEOWNERS
- test/system/registry-authentication/username-password.spec.ts
change codeowners after team split
> chore: update codeowners to team mycelium

- .circleci/config.yml
- .github/workflows/release-notes.yaml
following the change of the main branch from `master` to `main`, we need
to change some configs in circleci and release notes to adjust to this
change
> chore: update release branch to main

- package.json
explicitly set main as semantic release branch due to release failures
> chore: explicitly set main as semantic release branch

- .circleci/build-cli.sh
- .circleci/config.yml
We want to make sure that our changes can be used in Snyk's CLI. Added a
step in which we include the latest changes in the plugin into the CLI
and run the CLI build command.
> chore: build CLI in pipeline

- package.json
This PR upgrades snyk-docker-pull lib, to get its latest dependencies.
> fix: upgrade snyk-docker-pull lib

- .circleci/config.yml
- test/windows/plugin.spec.ts
Test has been renamed with the last PR that implemented support for all kinds of Go binaries...
> test: fix the recurring Go binaries test

- lib/extractor/index.ts
- lib/extractor/layer.ts
- lib/inputs/node/static.ts
- lib/inputs/php/static.ts
- lib/inputs/python/static.ts
- test/system/deleted-files.spec.ts
- test/system/static.test.ts
- [ V] Ready for review
- [ V] Follows CONTRIBUTING rules
Avoid checking Python poetry+pip, PHP, node, and Java files that have been deleted.
lib/extractor/index.ts
Added: test/system/deleted-files.spec.ts
https://snyksec.atlassian.net/browse/MYC-147
> feat: support deleted files

- .snyk
- lib/docker.ts
- lib/sub-process.ts
- package.json
> fix: quote spawn args

- package.json
This PR upgrades `snyk-nodejs-lockfile-parser`
> chore: update snyk-nodejs-lockfile-parser

- lib/analyzer/image-inspector.ts
- lib/analyzer/types.ts
- lib/extractor/image.ts
- lib/facts.ts
- lib/response-builder.ts
- lib/scan.ts
- lib/static.ts
- lib/types.ts
- package.json
- test/lib/extractor/image.spec.ts
- test/system/app-os/__snapshots__/globs.spec.ts.snap
- test/system/operating-systems/__snapshots__/alpine3.7.spec.ts.snap
- test/system/operating-systems/__snapshots__/busybox1.32.spec.ts.snap
- test/system/operating-systems/__snapshots__/centos6.spec.ts.snap
- test/system/operating-systems/__snapshots__/centos7.spec.ts.snap
- test/system/operating-systems/__snapshots__/debian9.spec.ts.snap
- test/system/operating-systems/__snapshots__/distroless.spec.ts.snap
- test/system/operating-systems/__snapshots__/oraclelinux8.2.spec.ts.snap
- test/system/operating-systems/__snapshots__/scratch.spec.ts.snap
- test/system/operating-systems/__snapshots__/sles15.spec.ts.snap
- test/system/operating-systems/__snapshots__/ubi8.spec.ts.snap
- test/system/package-managers/__snapshots__/apk.spec.ts.snap
- test/system/package-managers/__snapshots__/deb.spec.ts.snap
- test/system/package-managers/__snapshots__/rpm.spec.ts.snap
- test/system/platforms/__snapshots__/amd.spec.ts.snap
- test/system/platforms/__snapshots__/arm.spec.ts.snap
- test/system/platforms/__snapshots__/ppc64le.spec.ts.snap
- test/system/registry-authentication/__snapshots__/username-password.spec.ts.snap
Add new fact imageNames for Image Model service to store reference for the image.
https://snyksec.atlassian.net/browse/RUN-1928
> RUN-1928 feat: add new fact imageNames

- package-lock.json
- package.json
Update dependencies, as we update both libraries to Node 18:
* @snyk/docker-registry-v2-client
* @snyk/snyk-docker-pull
> CIT-243 fix: update dependencies

- components/common.yaml
Adds OpenAPI common components
> chore: add openapi common components

- components/common.yaml
* Update the data types in OpenAPI spec to accept any data type, to align with the typeScript definitions.
* Add support for kubernetes identity in Target OpenAPI spec
> chore: extend open api spec

- .circleci/config.yml
Add snyk scan code and snyk scan deps to the circle ci workflow.
[Jira Ticket](https://snyksec.atlassian.net/browse/LUM-445)
[SAST Scanning](https://snyksec.atlassian.net/wiki/spaces/PRODSEC/pages/1562411036/Static+Application+Security+Testing+SAST+Scanning#SAST-Scanning-Integrations)
> chore: add snyk scan code and deps to the circle ci workflow

- test/system/operating-systems/alpine3.7.spec.ts
- test/system/operating-systems/centos7.spec.ts
Fix tests empty catch for promises due to failures in CircleCI.
> fix: fix tests empty catch

- .circleci/config.yml
Bump CircleCI windows node version to 14
> chore: bump ci windows node version to 14

- package.json
> chore: remove tap unit test script

- lib/index.ts
export `parse dockerfile` functionality.
> feat: export parse dockerfile functionality

- package-lock.json
- package.json
feat: large layer support
updates library to a version that downloads layers directly to disk instead of memory. resolves high memory consumption and NodeJS buffer errors while trying to allocate 4GB+ buffers.
> feat: large layer support

- lib/analyzer/image-inspector.ts
- test/lib/analyzer/image-inspector.spec.ts
Adds support for images prepended with `docker.io/`.
> fix: handle docker io registry base

- .circleci/config.yml
- .github/CODEOWNERS
- catalog-info.yaml
Handover service to unify team.
- CODEOWNERS update
- catalog-info.yaml update
- Update external groups and slack channels 
[Jira Ticket](https://snyksec.atlassian.net/browse/TRACKER-81)
> chore: handover service to unify [TRACKER-81]

- package-lock.json
- package.json
**What does this PR do?**
Bump the `snyk-nodejs-lockfile-parser` dependency version.
> fix: upgrade nodejs parser dependency

- lib/analyzer/image-inspector.ts
- lib/docker.ts
- package-lock.json
- package.json
- test/lib/analyzer/image-inspector.spec.ts
- test/lib/docker.spec.ts
Adds support for passing the platform parameter when pulling an image from a registry without using the docker binary
> feat: support platform when pulling image from registry UNIFY-163

- .snyk
- test/lib/docker.spec.ts
> fix: updated dependencies to resolve vulnerabilities

- lib/sub-process.ts
- test/lib/sub-process.spec.ts
This PR introduces a change to the execute function in lib/sub-process.ts. It modifies how the environment is passed when spawning a sub-process.
Start by reviewing the changes in lib/sub-process.ts. Specifically, focus on the line:
```diff
+  const spawnOptions: any = { shell: true, env: { ...process.env } };
```
This line spreads the current process environment (process.env) into the spawnOptions object used for spawning sub-processes.
Next, review the new test file `test/lib/sub-process.spec.ts`. This test verifies that the environment remains unmodified after executing a sub-process with the updated execute function.
It's not ideal to manually test environment variables directly. However, you can review the existing test (test/lib/sub-process.spec.ts) for inspiration. You could …
> fix: do not overwrite values [CLI-543]

- .circleci/config.yml
- .snyk
- lib/analyzer/applications/node-modules-utils.ts
- lib/analyzer/applications/node.ts
- test/lib/docker.spec.ts
- test/system/application-scans/node.spec.ts
Fixes the possible unhandled promise rejection edge case and adds some additional input validation.
> fix: avoid possible unhandled promise rejections

- .circleci/config.yml
[PRODSEC-3273]: Update secrets scanning channel and snyk scan context for container team
-- 
Committed by prodsec-tools-v2 using octopilot
[PRODSEC-3273]: https://snyksec.atlassian.net/browse/PRODSEC-3273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PRODSEC-3273]: Update secrets scanning channel and snyk scan context for container team

- .snyk
- package-lock.json
- package.json
> fix: fix tar-fs high vulnerability CN-63

- lib/response-builder.ts
- lib/static.ts
- lib/types.ts
Passes target reference from cli options for scan to add target reference support for test flow.
> fix: add possible targetreference to plugin response

- .circleci/config.yml
- .github/CODEOWNERS
- catalog-info.yaml
Moves ownership to infrasec_container team.
> chore: move ownership to infrasec_container CN-88

- catalog-info.yaml
Updates the catalog-info spec's owner to container.
> chore: update spec owner to container

- test/system/operating-systems/__snapshots__/centos6.spec.ts.snap
- test/system/operating-systems/__snapshots__/centos7.spec.ts.snap
- test/system/operating-systems/centos6.spec.ts
- test/system/operating-systems/centos7.spec.ts
- test/system/package-managers/__snapshots__/rpm.spec.ts.snap
- test/system/package-managers/rpm.spec.ts
Fix the tests that were failing due to redhat updating the version and dropping the old one
I also added a mock for binaryPresent so the test will pass when run locally (no change when run on circleci)
> fix: fix the tests

- test/unit/pclntab.spec.ts
Added some tests to improve the test coverage for snyk-docker-plugin. `go-parser` specifically for this PR
Before:
After:
> chore: tests for pclntab

- test/fixtures/centos-shas.ts
- test/system/package-managers/__snapshots__/rpm.spec.ts.snap
Quay updated the shas again on me and broke the tests
> chore: screams internally

- package-lock.json
- package.json
> feat: add minimatch as production dependency
